# -*- coding: utf-8 -*-
"""Generate alphabetRoulette/js/perks.js from Roulette + KillerShop data."""
import json, re, os, sys

ROOT = r"D:\klaxix.xyz"

def load_js_object(path, prefix_re):
    with open(path, encoding="utf-8") as f:
        txt = f.read()
    txt = re.sub(r"^//.*\n", "", txt)
    txt = re.sub(prefix_re, "", txt, count=1)
    txt = txt.rstrip().rstrip(";")
    return json.loads(txt)

lib = load_js_object(os.path.join(ROOT, "Roulette", "data", "library.js"),
                     r"^window\.ROULETTE_DATA\s*=\s*")
shop = load_js_object(os.path.join(ROOT, "KillerShop", "js", "data.js"),
                      r"^window\.SHOP_DATA\s*=\s*")

# ---- quality lookup from KillerShop ----------------------------------------
# quality: 0 = green (tier 1), 1 = blue, 2 = purple
K_TIER_Q = {"S": 2, "A": 2, "B": 1, "C": 0, "D": 0}
S_TIER_Q = {"3": 2, "2": 1, "1": 0, "0": 0}

def norm(s):
    return re.sub(r"\s+", " ", s).strip().lower().replace("ё", "е")

# Ключ — английское имя из имени файла иконки: русские названия не уникальны
# (например, "МЕРТВАЯ ХВАТКА" = и Deadlock (тир A), и Iron Grasp (тир C)).
def stem(image_path):
    return norm(os.path.splitext(os.path.basename(image_path))[0].replace("_", "'"))

killer_q = {}
for tier, perks in shop["killerPerks"].items():
    for p in perks:
        killer_q[stem(p["img"])] = K_TIER_Q[tier]

surv_q = {}
for tier, perks in shop["survivorPerks"].items():
    for p in perks:
        surv_q[stem(p["img"])] = S_TIER_Q[tier]

# ---- EN display name from icon filename ------------------------------------
EN_PREFIX = ("Hex ", "Scourge Hook ", "Boon ", "Invocation ", "Teamwork ")

def en_name(image_path):
    stem = os.path.splitext(os.path.basename(image_path))[0]
    stem = stem.replace("_", "'")
    for pre in EN_PREFIX:
        if stem.startswith(pre):
            return pre.rstrip() + ": " + stem[len(pre):]
    return stem

# ---- build entries ----------------------------------------------------------
def build(pool, qmap, role):
    out, missing = [], []
    for p in pool:
        ru = re.sub(r"\s+", " ", p["name"]).strip()
        en = en_name(p["image"])
        q = qmap.get(stem(p["image"]))
        if q is None:
            q = 0
            missing.append(ru + " / " + en)
        out.append({"en": en, "ru": ru, "q": q, "owner": p.get("survivor", ""),
                    "icon": p["image"], "role": role})
    return out, missing

surv, surv_missing = build(lib["survivorPerkPool"], surv_q, "s")
kill, kill_missing = build(lib["killerPerkPool"], killer_q, "k")

print(f"survivor perks: {len(surv)}; not in shop (-> tier 1/green): {len(surv_missing)}")
for m in surv_missing: print("   S-", m)
print(f"killer perks:   {len(kill)}; not in shop (-> tier 1/green): {len(kill_missing)}")
for m in kill_missing: print("   K-", m)

# reverse check: shop perks that never matched a pool perk (typo detection)
pool_en = {stem(p["icon"]) for p in surv + kill}
unref = [n for n in list(surv_q) + list(killer_q) if n not in pool_en]
print(f"shop perks with no pool match: {len(unref)}")
for u in unref: print("   ?", u)

qc = {0: 0, 1: 0, 2: 0}
for p in surv + kill: qc[p["q"]] += 1
print("quality counts (green/blue/purple):", qc)

# ---- characters (тот же ростер с портретами, что в магазине убийцы) ---------
with open(os.path.join(ROOT, "Roulette", "data", "killer_map.json"), encoding="utf-8") as f:
    kmap = json.load(f)  # RU (верхний регистр) -> красивое EN имя

def char_en(entry, ru_to_en):
    en = ru_to_en.get(norm(entry["name"]))
    if en:
        return en
    return os.path.splitext(os.path.basename(entry["img"]))[0].replace("_", "'")

def build_chars(entries, ru_to_en):
    out = []
    for c in entries:
        # пути в data.js магазина заданы от KillerShop/ ("../assets/...") —
        # alphabetRoulette/ лежит на том же уровне, так что они работают как есть
        out.append({"ru": c["name"], "en": char_en(c, ru_to_en), "icon": c["img"]})
    return out

survivors = build_chars(shop["survivors"], {})
killers = build_chars(shop["killers"], {norm(k): v for k, v in kmap.items()})
no_en = [c["ru"] for c in killers if not kmap.get(c["ru"].upper()) and norm(c["ru"]) not in {norm(k) for k in kmap}]
print(f"characters: {len(survivors)} survivors, {len(killers)} killers; killers w/o map EN name: {no_en}")

# ---- emit -------------------------------------------------------------------
out_dir = os.path.join(ROOT, "alphabetRoulette", "js")
os.makedirs(out_dir, exist_ok=True)
payload = {"survivorPerks": surv, "killerPerks": kill,
           "survivors": survivors, "killers": killers}
with open(os.path.join(out_dir, "perks.js"), "w", encoding="utf-8") as f:
    f.write("// AUTO-GENERATED by tools/gen_perks.py — do not edit by hand.\n")
    f.write("// Source: Roulette/data/library.js (names) + KillerShop/js/data.js (quality).\n")
    f.write("// q: 0 = green (tier 1, not in killer shop), 1 = blue, 2 = purple.\n")
    f.write("window.ALPHABET_DATA = ")
    f.write(json.dumps(payload, ensure_ascii=False, indent=1))
    f.write(";\n")
print("written:", os.path.join(out_dir, "perks.js"))
