// AUTO-GENERATED by tools/gen_perks.py — do not edit by hand.
// Source: Roulette/data/library.js (names) + KillerShop/js/data.js (quality).
// q: 0 = green (tier 1, not in killer shop), 1 = blue, 2 = purple.
window.ALPHABET_DATA = {
 "survivorPerks": [
  {
   "en": "Inner Strength",
   "ru": "Внутренняя сила",
   "q": 0,
   "owner": "Нэнси Уиллер",
   "icon": "survivorPerks/Nancy Wheeler/Inner Strength.png",
   "role": "s"
  },
  {
   "en": "Adrenaline",
   "ru": "Адреналин",
   "q": 2,
   "owner": "Мэг Томас",
   "icon": "survivorPerks/Meg Thomas/Adrenaline.png",
   "role": "s"
  },
  {
   "en": "Apocalyptic Ingenuity",
   "ru": "Апокалиптическая смекалка",
   "q": 0,
   "owner": "Рик Граймс",
   "icon": "survivorPerks/Rick Grimes/Apocalyptic Ingenuity.png",
   "role": "s"
  },
  {
   "en": "Pharmacy",
   "ru": "Аптекарь",
   "q": 0,
   "owner": "Квентин Смит",
   "icon": "survivorPerks/Quentin Smith/Pharmacy.png",
   "role": "s"
  },
  {
   "en": "Bada Bada Boom",
   "ru": "Бада-бада-бум",
   "q": 0,
   "owner": "Дастин Хендерсон",
   "icon": "survivorPerks/Dustin Henderson/Bada Bada Boom.png",
   "role": "s"
  },
  {
   "en": "No Mither",
   "ru": "Без сожаления",
   "q": 0,
   "owner": "Дэвид Кинг",
   "icon": "survivorPerks/David King/No Mither.png",
   "role": "s"
  },
  {
   "en": "Off the Record",
   "ru": "Без огласки",
   "q": 1,
   "owner": "Зарина Кассир",
   "icon": "survivorPerks/Zarina Kassir/Off the Record.png",
   "role": "s"
  },
  {
   "en": "Vigil",
   "ru": "Бессонница",
   "q": 1,
   "owner": "Квентин Смит",
   "icon": "survivorPerks/Quentin Smith/Vigil.png",
   "role": "s"
  },
  {
   "en": "Shoulder the Burden",
   "ru": "Бремя на себя",
   "q": 2,
   "owner": "Тори Кейн",
   "icon": "survivorPerks/Taurie Cain/Shoulder the Burden.png",
   "role": "s"
  },
  {
   "en": "Rapid Response",
   "ru": "Быстрое реагирование",
   "q": 0,
   "owner": "Орела Роуз",
   "icon": "survivorPerks/Orela Rose/Rapid Response.png",
   "role": "s"
  },
  {
   "en": "Quick Gambit",
   "ru": "Быстрый гамбит",
   "q": 1,
   "owner": "Витторио Тоскано",
   "icon": "survivorPerks/Vittorio Toscano/Quick Gambit.png",
   "role": "s"
  },
  {
   "en": "Quick and Quiet",
   "ru": "Быстрый и тихий",
   "q": 0,
   "owner": "Мэг Томас",
   "icon": "survivorPerks/Meg Thomas/Quick and Quiet.png",
   "role": "s"
  },
  {
   "en": "Bardic Inspiration",
   "ru": "Вдохновение барда",
   "q": 0,
   "owner": "Аэстри Язар",
   "icon": "survivorPerks/Aestri Yazar/Bardic Inspiration.png",
   "role": "s"
  },
  {
   "en": "Lucky Break",
   "ru": "Везение",
   "q": 1,
   "owner": "Юи Кимура",
   "icon": "survivorPerks/Yui Kimura/Lucky Break.png",
   "role": "s"
  },
  {
   "en": "Visionary",
   "ru": "Визионер",
   "q": 0,
   "owner": "Феликс Рихтер",
   "icon": "survivorPerks/Felix Richter/Visionary.png",
   "role": "s"
  },
  {
   "en": "Blood Rush",
   "ru": "Выше головы",
   "q": 0,
   "owner": "Ренато Лира",
   "icon": "survivorPerks/Renato Lyra/Blood Rush.png",
   "role": "s"
  },
  {
   "en": "Lithe",
   "ru": "Гибкость",
   "q": 2,
   "owner": "Фенг Мин",
   "icon": "survivorPerks/Feng Min/Lithe.png",
   "role": "s"
  },
  {
   "en": "Eyes of Belmont",
   "ru": "Глаза Бельмонта",
   "q": 0,
   "owner": "Тревор Бельмонт",
   "icon": "survivorPerks/Trevor Belmont/Eyes of Belmont.png",
   "role": "s"
  },
  {
   "en": "Urban Evasion",
   "ru": "Городской бег",
   "q": 0,
   "owner": "Нея Карлссон",
   "icon": "survivorPerks/Nea Karlsson/Urban Evasion.png",
   "role": "s"
  },
  {
   "en": "Boon: Circle of Healing",
   "ru": "Дар: Круг исцеления",
   "q": 1,
   "owner": "Микаэла Рид",
   "icon": "survivorPerks/Mikaela Reid/Boon Circle of Healing.png",
   "role": "s"
  },
  {
   "en": "Illumination",
   "ru": "Дар: Освещение",
   "q": 0,
   "owner": "Алан Уэйк",
   "icon": "survivorPerks/Alan Wake/Illumination.png",
   "role": "s"
  },
  {
   "en": "Dark Theory",
   "ru": "Дар: Теория мрака",
   "q": 0,
   "owner": "Ёити Асакава",
   "icon": "survivorPerks/Yoichi Asakawa/Dark Theory.png",
   "role": "s"
  },
  {
   "en": "Boon: Shadow Step",
   "ru": "Дар: Уход в тень",
   "q": 0,
   "owner": "Микаэла Рид",
   "icon": "survivorPerks/Mikaela Reid/Boon Shadow Step.png",
   "role": "s"
  },
  {
   "en": "Champion of Light",
   "ru": "Воин света",
   "q": 0,
   "owner": "Алан Уэйк",
   "icon": "survivorPerks/Alan Wake/Champion of Light.png",
   "role": "s"
  },
  {
   "en": "Extrasensory Perception",
   "ru": "Восприятие экстрасенса",
   "q": 0,
   "owner": "Одиннадцать",
   "icon": "survivorPerks/Eleven/Extrasensory Perception.png",
   "role": "s"
  },
  {
   "en": "Plot Twist",
   "ru": "Вот это поворот",
   "q": 2,
   "owner": "Николас Кейдж",
   "icon": "survivorPerks/Nicolas Cage/Plot Twist.png",
   "role": "s"
  },
  {
   "en": "Duty Of Care",
   "ru": "Врачебный долг",
   "q": 1,
   "owner": "Орела Роуз",
   "icon": "survivorPerks/Orela Rose/Duty Of Care.png",
   "role": "s"
  },
  {
   "en": "Second Wind",
   "ru": "Второе дыхание",
   "q": 1,
   "owner": "Стив Харрингтон",
   "icon": "survivorPerks/Steve Harrington/Second Wind.png",
   "role": "s"
  },
  {
   "en": "Tenacity",
   "ru": "Выдержка",
   "q": 0,
   "owner": "Детектив Тэпп",
   "icon": "survivorPerks/David Tapp/Tenacity.png",
   "role": "s"
  },
  {
   "en": "Stake Out",
   "ru": "Выслеживание подозреваемого",
   "q": 1,
   "owner": "Детектив Тэпп",
   "icon": "survivorPerks/David Tapp/Stake Out.png",
   "role": "s"
  },
  {
   "en": "Hardened",
   "ru": "Закалка",
   "q": 0,
   "owner": "Лара Крофт",
   "icon": "survivorPerks/Lara Croft/Hardened.png",
   "role": "s"
  },
  {
   "en": "Boon: Exponential",
   "ru": "Дар: Экспонента",
   "q": 0,
   "owner": "Хонас Васкес",
   "icon": "survivorPerks/Jonah Vasquez/Boon Exponential.png",
   "role": "s"
  },
  {
   "en": "Deadline",
   "ru": "Дедлайн",
   "q": 0,
   "owner": "Алан Уэйк",
   "icon": "survivorPerks/Alan Wake/Deadline.png",
   "role": "s"
  },
  {
   "en": "Deja Vu",
   "ru": "Дежавю",
   "q": 2,
   "owner": "Навык",
   "icon": "survivorPerks/General Survivor/Deja Vu.png",
   "role": "s"
  },
  {
   "en": "Wicked",
   "ru": "Дерзость",
   "q": 0,
   "owner": "Сейбл Уорд",
   "icon": "survivorPerks/Sable Ward/Wicked.png",
   "role": "s"
  },
  {
   "en": "Detective's Hunch",
   "ru": "Детективное чутье",
   "q": 0,
   "owner": "Детектив Тэпп",
   "icon": "survivorPerks/David Tapp/Detective_s Hunch.png",
   "role": "s"
  },
  {
   "en": "Diversion",
   "ru": "Диверсия",
   "q": 0,
   "owner": "Адам Фрэнсис",
   "icon": "survivorPerks/Adam Francis/Diversion.png",
   "role": "s"
  },
  {
   "en": "Dramaturgy",
   "ru": "Драматургия",
   "q": 2,
   "owner": "Николас Кейдж",
   "icon": "survivorPerks/Nicolas Cage/Dramaturgy.png",
   "role": "s"
  },
  {
   "en": "Friendly Competition",
   "ru": "Дружеское состязание",
   "q": 0,
   "owner": "Талита Лира",
   "icon": "survivorPerks/Thalita Lyra/Friendly Competition.png",
   "role": "s"
  },
  {
   "en": "Rookie Spirit",
   "ru": "Дух новичка",
   "q": 0,
   "owner": "Леон С. Кеннеди",
   "icon": "survivorPerks/Leon S Kennedy/Rookie Spirit.png",
   "role": "s"
  },
  {
   "en": "Sole Survivor",
   "ru": "Единственный выживший",
   "q": 0,
   "owner": "Лори Строуд",
   "icon": "survivorPerks/Laurie Strode/Sole Survivor.png",
   "role": "s"
  },
  {
   "en": "Iron Will",
   "ru": "Железная воля",
   "q": 1,
   "owner": "Джейк Парк",
   "icon": "survivorPerks/Jake Park/Iron Will.png",
   "role": "s"
  },
  {
   "en": "Road Life",
   "ru": "Жизнь в дороге",
   "q": 0,
   "owner": "Ви Бунясак",
   "icon": "survivorPerks/Vee Boonyasak/Road Life.png",
   "role": "s"
  },
  {
   "en": "Wiretap",
   "ru": "Жучок",
   "q": 0,
   "owner": "Ада Вонг",
   "icon": "survivorPerks/Ada Wong/Wiretap.png",
   "role": "s"
  },
  {
   "en": "Fast Track",
   "ru": "За чужой счет",
   "q": 0,
   "owner": "Ли Юнчин",
   "icon": "survivorPerks/Yun-Jin Lee/Fast Track.png",
   "role": "s"
  },
  {
   "en": "Teamwork: Toughen Up",
   "ru": "Командная работа: Собраться с силами",
   "q": 0,
   "owner": "Рик Граймс",
   "icon": "survivorPerks/Rick Grimes/Teamwork Toughen Up.png",
   "role": "s"
  },
  {
   "en": "Still Sight",
   "ru": "Замри и увидишь",
   "q": 0,
   "owner": "Аэстри Язар",
   "icon": "survivorPerks/Aestri Yazar/Still Sight.png",
   "role": "s"
  },
  {
   "en": "Background Player",
   "ru": "Запасной игрок",
   "q": 1,
   "owner": "Ренато Лира",
   "icon": "survivorPerks/Renato Lyra/Background Player.png",
   "role": "s"
  },
  {
   "en": "Ghost Notes",
   "ru": "Записки о призраке",
   "q": 1,
   "owner": "Ви Бунясак",
   "icon": "survivorPerks/Vee Boonyasak/Ghost Notes.png",
   "role": "s"
  },
  {
   "en": "Mirrored Illusion",
   "ru": "Зеркальная иллюзия",
   "q": 0,
   "owner": "Аэстри Язар",
   "icon": "survivorPerks/Aestri Yazar/Mirrored Illusion.png",
   "role": "s"
  },
  {
   "en": "Open-Handed",
   "ru": "Игра в открытую",
   "q": 0,
   "owner": "Эйс Висконти",
   "icon": "survivorPerks/Ace Visconti/Open-Handed.png",
   "role": "s"
  },
  {
   "en": "Change of Plan",
   "ru": "Изменение плана",
   "q": 0,
   "owner": "Дастин Хендерсон",
   "icon": "survivorPerks/Dustin Henderson/Change of Plan.png",
   "role": "s"
  },
  {
   "en": "Appraisal",
   "ru": "Изучение",
   "q": 0,
   "owner": "Элоди Ракото",
   "icon": "survivorPerks/Elodie Rakoto/Appraisal.png",
   "role": "s"
  },
  {
   "en": "Distortion",
   "ru": "Искажение",
   "q": 0,
   "owner": "Джефф Йохансен",
   "icon": "survivorPerks/Jeff Johansen/Distortion.png",
   "role": "s"
  },
  {
   "en": "Better Than New",
   "ru": "Как новенький",
   "q": 0,
   "owner": "Ребекка Чемберс",
   "icon": "survivorPerks/Rebecca Chambers/Better Than New.png",
   "role": "s"
  },
  {
   "en": "Teamwork: Throw Down",
   "ru": "Командная работа: Скромная победа",
   "q": 0,
   "owner": "Мишон Граймс",
   "icon": "survivorPerks/Michonne Grimes/Teamwork Throw Down.png",
   "role": "s"
  },
  {
   "en": "Teamwork: Soft Spoken",
   "ru": "Командная работа: Приглушение",
   "q": 0,
   "owner": "Одиннадцать",
   "icon": "survivorPerks/Eleven/Teamwork Soft Spoken.png",
   "role": "s"
  },
  {
   "en": "Teamwork: Full Circuit",
   "ru": "Командная работа: Полная схема",
   "q": 0,
   "owner": "Дастин Хендерсон",
   "icon": "survivorPerks/Dustin Henderson/Teamwork Full Circuit.png",
   "role": "s"
  },
  {
   "en": "Teamwork: Collective Stealth",
   "ru": "Командная работа: Общая скрытность",
   "q": 0,
   "owner": "Ренато Лира",
   "icon": "survivorPerks/Renato Lyra/Teamwork Collective Stealth.png",
   "role": "s"
  },
  {
   "en": "Teamwork: Power of Two",
   "ru": "Командная работа: Быстрая пара",
   "q": 0,
   "owner": "Талита Лира",
   "icon": "survivorPerks/Thalita Lyra/Teamwork Power of Two.png",
   "role": "s"
  },
  {
   "en": "A Place For Us",
   "ru": "Место для нас",
   "q": 0,
   "owner": "Квон Тхэён",
   "icon": "survivorPerks/Kwon Tae-young/A Place For Us.png",
   "role": "s"
  },
  {
   "en": "Corrective Action",
   "ru": "Корректировка",
   "q": 0,
   "owner": "Хонас Васкес",
   "icon": "survivorPerks/Jonah Vasquez/Corrective Action.png",
   "role": "s"
  },
  {
   "en": "Dead Hard",
   "ru": "Крепкий орешек",
   "q": 2,
   "owner": "Дэвид Кинг",
   "icon": "survivorPerks/David King/Dead Hard.png",
   "role": "s"
  },
  {
   "en": "Blood Pact",
   "ru": "Кровавый договор",
   "q": 0,
   "owner": "Шерил Мейсон",
   "icon": "survivorPerks/Cheryl Mason/Blood Pact.png",
   "role": "s"
  },
  {
   "en": "Kindred",
   "ru": "Кровные узы",
   "q": 0,
   "owner": "Навык",
   "icon": "survivorPerks/General Survivor/Kindred.png",
   "role": "s"
  },
  {
   "en": "Saboteur",
   "ru": "Крушитель",
   "q": 0,
   "owner": "Джейк Парк",
   "icon": "survivorPerks/Jake Park/Saboteur.png",
   "role": "s"
  },
  {
   "en": "Lightweight",
   "ru": "Легковес",
   "q": 0,
   "owner": "Навык",
   "icon": "survivorPerks/General Survivor/Lightweight.png",
   "role": "s"
  },
  {
   "en": "Light-Footed",
   "ru": "Легкоступ",
   "q": 0,
   "owner": "Эллен Рипли",
   "icon": "survivorPerks/Ellen Ripley/Light-Footed.png",
   "role": "s"
  },
  {
   "en": "Leader",
   "ru": "Лидер",
   "q": 1,
   "owner": "Дуайт Фэйрфилд",
   "icon": "survivorPerks/Dwight Fairfield/Leader.png",
   "role": "s"
  },
  {
   "en": "Exultation",
   "ru": "Ликование",
   "q": 0,
   "owner": "Тревор Бельмонт",
   "icon": "survivorPerks/Trevor Belmont/Exultation.png",
   "role": "s"
  },
  {
   "en": "Balanced Landing",
   "ru": "Ловкое приземление",
   "q": 2,
   "owner": "Нея Карлссон",
   "icon": "survivorPerks/Nea Karlsson/Balanced Landing.png",
   "role": "s"
  },
  {
   "en": "Better Together",
   "ru": "Лучше вместе",
   "q": 0,
   "owner": "Нэнси Уиллер",
   "icon": "survivorPerks/Nancy Wheeler/Better Together.png",
   "role": "s"
  },
  {
   "en": "Any Means Necessary",
   "ru": "Любыми средствами",
   "q": 0,
   "owner": "Юи Кимура",
   "icon": "survivorPerks/Yui Kimura/Any Means Necessary.png",
   "role": "s"
  },
  {
   "en": "Plunderer's Instinct",
   "ru": "Мародерское чутье",
   "q": 0,
   "owner": "Навык",
   "icon": "survivorPerks/General Survivor/Plunderer_s Instinct.png",
   "role": "s"
  },
  {
   "en": "Small Game",
   "ru": "Мелкая дичь",
   "q": 0,
   "owner": "Навык",
   "icon": "survivorPerks/General Survivor/Small Game.png",
   "role": "s"
  },
  {
   "en": "Moment of Glory",
   "ru": "Момент славы",
   "q": 0,
   "owner": "Тревор Бельмонт",
   "icon": "survivorPerks/Trevor Belmont/Moment of Glory.png",
   "role": "s"
  },
  {
   "en": "Spine Chill",
   "ru": "Мурашки по спине",
   "q": 0,
   "owner": "Навык",
   "icon": "survivorPerks/General Survivor/Spine Chill.png",
   "role": "s"
  },
  {
   "en": "We're Gonna Live Forever",
   "ru": "Мы будем жить вечно",
   "q": 1,
   "owner": "Дэвид Кинг",
   "icon": "survivorPerks/David King/We_re Gonna Live Forever.png",
   "role": "s"
  },
  {
   "en": "We'll Make It",
   "ru": "Мы справимся",
   "q": 1,
   "owner": "Навык",
   "icon": "survivorPerks/General Survivor/We_ll Make It.png",
   "role": "s"
  },
  {
   "en": "We See You",
   "ru": "Мы тебя видим",
   "q": 0,
   "owner": "Одиннадцать",
   "icon": "survivorPerks/Eleven/We See You.png",
   "role": "s"
  },
  {
   "en": "Cut Loose",
   "ru": "На волю",
   "q": 0,
   "owner": "Талита Лира",
   "icon": "survivorPerks/Thalita Lyra/Cut Loose.png",
   "role": "s"
  },
  {
   "en": "Five Moves Ahead",
   "ru": "На пять шагов впереди",
   "q": 1,
   "owner": "Квон Тхэён",
   "icon": "survivorPerks/Kwon Tae-young/Five Moves Ahead.png",
   "role": "s"
  },
  {
   "en": "Hope",
   "ru": "Надежда",
   "q": 1,
   "owner": "Навык",
   "icon": "survivorPerks/General Survivor/Hope.png",
   "role": "s"
  },
  {
   "en": "Head On",
   "ru": "Напролом",
   "q": 1,
   "owner": "Джейн Ромеро",
   "icon": "survivorPerks/Jane Romero/Head On.png",
   "role": "s"
  },
  {
   "en": "Do No Harm",
   "ru": "Не навреди",
   "q": 0,
   "owner": "Орела Роуз",
   "icon": "survivorPerks/Orela Rose/Do No Harm.png",
   "role": "s"
  },
  {
   "en": "Unbreakable",
   "ru": "Несокрушимый",
   "q": 2,
   "owner": "Уильям «Билл» Овербек",
   "icon": "survivorPerks/Bill Overbeck/Unbreakable.png",
   "role": "s"
  },
  {
   "en": "Low Profile",
   "ru": "Ниже травы",
   "q": 0,
   "owner": "Ада Вонг",
   "icon": "survivorPerks/Ada Wong/Low Profile.png",
   "role": "s"
  },
  {
   "en": "No One Left Behind",
   "ru": "Никто не остался позади",
   "q": 0,
   "owner": "Навык",
   "icon": "survivorPerks/General Survivor/No One Left Behind.png",
   "role": "s"
  },
  {
   "en": "Babysitter",
   "ru": "Нянька",
   "q": 0,
   "owner": "Стив Харрингтон",
   "icon": "survivorPerks/Steve Harrington/Babysitter.png",
   "role": "s"
  },
  {
   "en": "Soul Guard",
   "ru": "Оберег души",
   "q": 0,
   "owner": "Шерил Мейсон",
   "icon": "survivorPerks/Cheryl Mason/Soul Guard.png",
   "role": "s"
  },
  {
   "en": "Resurgence",
   "ru": "Поправка",
   "q": 2,
   "owner": "Джилл Валентайн",
   "icon": "survivorPerks/Jill Valentine/Resurgence.png",
   "role": "s"
  },
  {
   "en": "Red Herring",
   "ru": "Обман во благо",
   "q": 0,
   "owner": "Зарина Кассир",
   "icon": "survivorPerks/Zarina Kassir/Red Herring.png",
   "role": "s"
  },
  {
   "en": "Reassurance",
   "ru": "Ободрение",
   "q": 1,
   "owner": "Ребекка Чемберс",
   "icon": "survivorPerks/Rebecca Chambers/Reassurance.png",
   "role": "s"
  },
  {
   "en": "Object of Obsession",
   "ru": "Объект одержимости",
   "q": 0,
   "owner": "Лори Строуд",
   "icon": "survivorPerks/Laurie Strode/Object of Obsession.png",
   "role": "s"
  },
  {
   "en": "Borrowed Time",
   "ru": "Одолженное время",
   "q": 0,
   "owner": "Уильям «Билл» Овербек",
   "icon": "survivorPerks/Bill Overbeck/Borrowed Time.png",
   "role": "s"
  },
  {
   "en": "Deliverance",
   "ru": "Освобождение",
   "q": 2,
   "owner": "Адам Фрэнсис",
   "icon": "survivorPerks/Adam Francis/Deliverance.png",
   "role": "s"
  },
  {
   "en": "Left Behind",
   "ru": "Оставленный позади",
   "q": 0,
   "owner": "Уильям «Билл» Овербек",
   "icon": "survivorPerks/Bill Overbeck/Left Behind.png",
   "role": "s"
  },
  {
   "en": "Residual Manifest",
   "ru": "Остаточное проявление",
   "q": 0,
   "owner": "Хэдди Каур",
   "icon": "survivorPerks/Haddie Kaur/Residual Manifest.png",
   "role": "s"
  },
  {
   "en": "Power Struggle",
   "ru": "Отчаянная борьба",
   "q": 0,
   "owner": "Элоди Ракото",
   "icon": "survivorPerks/Elodie Rakoto/Power Struggle.png",
   "role": "s"
  },
  {
   "en": "Desperate Measures",
   "ru": "Отчаянные меры",
   "q": 0,
   "owner": "Феликс Рихтер",
   "icon": "survivorPerks/Felix Richter/Desperate Measures.png",
   "role": "s"
  },
  {
   "en": "Scene Partner",
   "ru": "Партнер по сцене",
   "q": 0,
   "owner": "Николас Кейдж",
   "icon": "survivorPerks/Nicolas Cage/Scene Partner.png",
   "role": "s"
  },
  {
   "en": "Up the Ante",
   "ru": "Повысить ставки",
   "q": 0,
   "owner": "Эйс Висконти",
   "icon": "survivorPerks/Ace Visconti/Up the Ante.png",
   "role": "s"
  },
  {
   "en": "Botany Knowledge",
   "ru": "Познания в ботанике",
   "q": 1,
   "owner": "Клодетт Морель",
   "icon": "survivorPerks/Claudette Morel/Botany Knowledge.png",
   "role": "s"
  },
  {
   "en": "Hyperfocus",
   "ru": "Полная сосредоточенность",
   "q": 2,
   "owner": "Ребекка Чемберс",
   "icon": "survivorPerks/Rebecca Chambers/Hyperfocus.png",
   "role": "s"
  },
  {
   "en": "Breakdown",
   "ru": "Поломка",
   "q": 0,
   "owner": "Джефф Йохансен",
   "icon": "survivorPerks/Jeff Johansen/Breakdown.png",
   "role": "s"
  },
  {
   "en": "Poised",
   "ru": "Равновесие",
   "q": 0,
   "owner": "Джейн Ромеро",
   "icon": "survivorPerks/Jane Romero/Poised.png",
   "role": "s"
  },
  {
   "en": "For the People",
   "ru": "Ради людей",
   "q": 1,
   "owner": "Зарина Кассир",
   "icon": "survivorPerks/Zarina Kassir/For the People.png",
   "role": "s"
  },
  {
   "en": "Last Stand",
   "ru": "Последний рубеж",
   "q": 0,
   "owner": "Мишон Граймс",
   "icon": "survivorPerks/Michonne Grimes/Last Stand.png",
   "role": "s"
  },
  {
   "en": "Reactive Healing",
   "ru": "Поспешное лечение",
   "q": 0,
   "owner": "Ада Вонг",
   "icon": "survivorPerks/Ada Wong/Reactive Healing.png",
   "role": "s"
  },
  {
   "en": "Dance With Me",
   "ru": "Потанцуй со мной",
   "q": 1,
   "owner": "Кейт Денсон",
   "icon": "survivorPerks/Kate Denson/Dance With Me.png",
   "role": "s"
  },
  {
   "en": "Potential Energy",
   "ru": "Потенциальная энергия",
   "q": 0,
   "owner": "Витторио Тоскано",
   "icon": "survivorPerks/Vittorio Toscano/Potential Energy.png",
   "role": "s"
  },
  {
   "en": "Premonition",
   "ru": "Предчувствие",
   "q": 0,
   "owner": "Навык",
   "icon": "survivorPerks/General Survivor/Premonition.png",
   "role": "s"
  },
  {
   "en": "Overcome",
   "ru": "Преодоление",
   "q": 2,
   "owner": "Хонас Васкес",
   "icon": "survivorPerks/Jonah Vasquez/Overcome.png",
   "role": "s"
  },
  {
   "en": "Made For This",
   "ru": "Призвание",
   "q": 0,
   "owner": "Габриэль Сома",
   "icon": "survivorPerks/Gabriel Soma/Made For This.png",
   "role": "s"
  },
  {
   "en": "Buckle Up",
   "ru": "Пристегнись",
   "q": 0,
   "owner": "Эшли Джей Уильямс",
   "icon": "survivorPerks/Ash Williams/Buckle Up.png",
   "role": "s"
  },
  {
   "en": "Mettle of Man",
   "ru": "Проверка на прочность",
   "q": 0,
   "owner": "Эшли Джей Уильямс",
   "icon": "survivorPerks/Ash Williams/Mettle of Man.png",
   "role": "s"
  },
  {
   "en": "Wake Up",
   "ru": "Проснись",
   "q": 0,
   "owner": "Квентин Смит",
   "icon": "survivorPerks/Quentin Smith/Wake Up.png",
   "role": "s"
  },
  {
   "en": "Counterforce",
   "ru": "Противодействие",
   "q": 0,
   "owner": "Джилл Валентайн",
   "icon": "survivorPerks/Jill Valentine/Counterforce.png",
   "role": "s"
  },
  {
   "en": "Prove Thyself",
   "ru": "Прояви себя",
   "q": 1,
   "owner": "Дуайт Фэйрфилд",
   "icon": "survivorPerks/Dwight Fairfield/Prove Thyself.png",
   "role": "s"
  },
  {
   "en": "One-Two-Three-Four",
   "ru": "Раз, два, три, четыре!",
   "q": 1,
   "owner": "Ви Бунясак",
   "icon": "survivorPerks/Vee Boonyasak/One-Two-Three-Four.png",
   "role": "s"
  },
  {
   "en": "Flashbang",
   "ru": "Световая граната",
   "q": 0,
   "owner": "Леон С. Кеннеди",
   "icon": "survivorPerks/Leon S Kennedy/Flashbang.png",
   "role": "s"
  },
  {
   "en": "Bond",
   "ru": "Связь",
   "q": 0,
   "owner": "Дуайт Фэйрфилд",
   "icon": "survivorPerks/Dwight Fairfield/Bond.png",
   "role": "s"
  },
  {
   "en": "Strength in Shadows",
   "ru": "Сила во мраке",
   "q": 0,
   "owner": "Сейбл Уорд",
   "icon": "survivorPerks/Sable Ward/Strength in Shadows.png",
   "role": "s"
  },
  {
   "en": "Slippery Meat",
   "ru": "Скользкое мясо",
   "q": 0,
   "owner": "Навык",
   "icon": "survivorPerks/General Survivor/Slippery Meat.png",
   "role": "s"
  },
  {
   "en": "Repressed Alliance",
   "ru": "Скрытый союз",
   "q": 0,
   "owner": "Шерил Мейсон",
   "icon": "survivorPerks/Cheryl Mason/Repressed Alliance.png",
   "role": "s"
  },
  {
   "en": "Finesse",
   "ru": "Сноровка",
   "q": 1,
   "owner": "Лара Крофт",
   "icon": "survivorPerks/Lara Croft/Finesse.png",
   "role": "s"
  },
  {
   "en": "Inner Focus",
   "ru": "Собранность",
   "q": 0,
   "owner": "Хэдди Каур",
   "icon": "survivorPerks/Haddie Kaur/Inner Focus.png",
   "role": "s"
  },
  {
   "en": "Flip Flop",
   "ru": "Раскачка",
   "q": 0,
   "owner": "Эшли Джей Уильямс",
   "icon": "survivorPerks/Ash Williams/Flip Flop.png",
   "role": "s"
  },
  {
   "en": "Troubleshooter",
   "ru": "Ремонтник",
   "q": 0,
   "owner": "Габриэль Сома",
   "icon": "survivorPerks/Gabriel Soma/Troubleshooter.png",
   "role": "s"
  },
  {
   "en": "Decisive Strike",
   "ru": "Решающий удар",
   "q": 2,
   "owner": "Лори Строуд",
   "icon": "survivorPerks/Laurie Strode/Decisive Strike.png",
   "role": "s"
  },
  {
   "en": "Parental Guidence",
   "ru": "Родительская забота",
   "q": 0,
   "owner": "Ёити Асакава",
   "icon": "survivorPerks/Yoichi Asakawa/Parental Guidence.png",
   "role": "s"
  },
  {
   "en": "Clean Break",
   "ru": "С чистого листа",
   "q": 1,
   "owner": "Тори Кейн",
   "icon": "survivorPerks/Taurie Cain/Clean Break.png",
   "role": "s"
  },
  {
   "en": "Self Care",
   "ru": "Сам себе доктор",
   "q": 0,
   "owner": "Клодетт Морель",
   "icon": "survivorPerks/Claudette Morel/Self Care.png",
   "role": "s"
  },
  {
   "en": "Self Preservation",
   "ru": "Самосохранение",
   "q": 0,
   "owner": "Ли Юнчин",
   "icon": "survivorPerks/Yun-Jin Lee/Self Preservation.png",
   "role": "s"
  },
  {
   "en": "Autodidact",
   "ru": "Самоучка",
   "q": 1,
   "owner": "Адам Фрэнсис",
   "icon": "survivorPerks/Adam Francis/Autodidact.png",
   "role": "s"
  },
  {
   "en": "Solidarity",
   "ru": "Солидарность",
   "q": 0,
   "owner": "Джейн Ромеро",
   "icon": "survivorPerks/Jane Romero/Solidarity.png",
   "role": "s"
  },
  {
   "en": "Flow State",
   "ru": "Состояние потока",
   "q": 1,
   "owner": "Квон Тхэён",
   "icon": "survivorPerks/Kwon Tae-young/Flow State.png",
   "role": "s"
  },
  {
   "en": "Empathy",
   "ru": "Сострадание",
   "q": 0,
   "owner": "Клодетт Морель",
   "icon": "survivorPerks/Claudette Morel/Empathy.png",
   "role": "s"
  },
  {
   "en": "Specialist",
   "ru": "Специалист",
   "q": 0,
   "owner": "Лара Крофт",
   "icon": "survivorPerks/Lara Croft/Specialist.png",
   "role": "s"
  },
  {
   "en": "Calm Spirit",
   "ru": "Спокойствие духа",
   "q": 0,
   "owner": "Джейк Парк",
   "icon": "survivorPerks/Jake Park/Calm Spirit.png",
   "role": "s"
  },
  {
   "en": "Sprint Burst",
   "ru": "Спринтер",
   "q": 2,
   "owner": "Мэг Томас",
   "icon": "survivorPerks/Meg Thomas/Sprint Burst.png",
   "role": "s"
  },
  {
   "en": "Bite the Bullet",
   "ru": "Стиснув зубы",
   "q": 0,
   "owner": "Леон С. Кеннеди",
   "icon": "survivorPerks/Leon S Kennedy/Bite the Bullet.png",
   "role": "s"
  },
  {
   "en": "Built to Last",
   "ru": "Строим на века",
   "q": 0,
   "owner": "Феликс Рихтер",
   "icon": "survivorPerks/Felix Richter/Built to Last.png",
   "role": "s"
  },
  {
   "en": "Lucky Star",
   "ru": "Счастливая звезда",
   "q": 0,
   "owner": "Эллен Рипли",
   "icon": "survivorPerks/Ellen Ripley/Lucky Star.png",
   "role": "s"
  },
  {
   "en": "Dark Sense",
   "ru": "Темное чувство",
   "q": 0,
   "owner": "Навык",
   "icon": "survivorPerks/General Survivor/Dark Sense.png",
   "role": "s"
  },
  {
   "en": "Technician",
   "ru": "Техник",
   "q": 0,
   "owner": "Фенг Мин",
   "icon": "survivorPerks/Feng Min/Technician.png",
   "role": "s"
  },
  {
   "en": "Camaraderie",
   "ru": "Товарищество",
   "q": 0,
   "owner": "Стив Харрингтон",
   "icon": "survivorPerks/Steve Harrington/Camaraderie.png",
   "role": "s"
  },
  {
   "en": "Alert",
   "ru": "Тревога",
   "q": 0,
   "owner": "Фенг Мин",
   "icon": "survivorPerks/Feng Min/Alert.png",
   "role": "s"
  },
  {
   "en": "Ace in the Hole",
   "ru": "Туз в рукаве",
   "q": 0,
   "owner": "Эйс Висконти",
   "icon": "survivorPerks/Ace Visconti/Ace in the Hole.png",
   "role": "s"
  },
  {
   "en": "Conviction",
   "ru": "Убежденность",
   "q": 0,
   "owner": "Мишон Граймс",
   "icon": "survivorPerks/Michonne Grimes/Conviction.png",
   "role": "s"
  },
  {
   "en": "Overzealous",
   "ru": "Усердие",
   "q": 0,
   "owner": "Хэдди Каур",
   "icon": "survivorPerks/Haddie Kaur/Overzealous.png",
   "role": "s"
  },
  {
   "en": "Resilience",
   "ru": "Устойчивость",
   "q": 1,
   "owner": "Навык",
   "icon": "survivorPerks/General Survivor/Resilience.png",
   "role": "s"
  },
  {
   "en": "Scavenger",
   "ru": "Утилизатор",
   "q": 0,
   "owner": "Габриэль Сома",
   "icon": "survivorPerks/Gabriel Soma/Scavenger.png",
   "role": "s"
  },
  {
   "en": "Aftercare",
   "ru": "Уход за больным",
   "q": 0,
   "owner": "Джефф Йохансен",
   "icon": "survivorPerks/Jeff Johansen/Aftercare.png",
   "role": "s"
  },
  {
   "en": "Fixated",
   "ru": "Фиксация",
   "q": 0,
   "owner": "Нэнси Уиллер",
   "icon": "survivorPerks/Nancy Wheeler/Fixated.png",
   "role": "s"
  },
  {
   "en": "Breakout",
   "ru": "Форсаж",
   "q": 0,
   "owner": "Юи Кимура",
   "icon": "survivorPerks/Yui Kimura/Breakout.png",
   "role": "s"
  },
  {
   "en": "Blast Mine",
   "ru": "Фугасная мина",
   "q": 0,
   "owner": "Джилл Валентайн",
   "icon": "survivorPerks/Jill Valentine/Blast Mine.png",
   "role": "s"
  },
  {
   "en": "Chemical Trap",
   "ru": "Химическая ловушка",
   "q": 0,
   "owner": "Эллен Рипли",
   "icon": "survivorPerks/Ellen Ripley/Chemical Trap.png",
   "role": "s"
  },
  {
   "en": "Invocation: Treacherous Crows",
   "ru": "Чары «Предательские вороны»",
   "q": 0,
   "owner": "Тори Кейн",
   "icon": "survivorPerks/Taurie Cain/Invocation Treacherous Crows.png",
   "role": "s"
  },
  {
   "en": "Invocation: Weaving Spiders",
   "ru": "Чары: Пауки-прядильщики",
   "q": 0,
   "owner": "Сейбл Уорд",
   "icon": "survivorPerks/Sable Ward/Invocation Weaving Spiders.png",
   "role": "s"
  },
  {
   "en": "Smash Hit",
   "ru": "Ударный забег",
   "q": 2,
   "owner": "Ли Юнчин",
   "icon": "survivorPerks/Yun-Jin Lee/Smash Hit.png",
   "role": "s"
  },
  {
   "en": "Deception",
   "ru": "Уловка",
   "q": 0,
   "owner": "Элоди Ракото",
   "icon": "survivorPerks/Elodie Rakoto/Deception.png",
   "role": "s"
  },
  {
   "en": "Fogwise",
   "ru": "Умудренный туманом",
   "q": 0,
   "owner": "Витторио Тоскано",
   "icon": "survivorPerks/Vittorio Toscano/Fogwise.png",
   "role": "s"
  },
  {
   "en": "Windows of Opportunity",
   "ru": "Уникальная возможность",
   "q": 1,
   "owner": "Кейт Денсон",
   "icon": "survivorPerks/Kate Denson/Windows of Opportunity.png",
   "role": "s"
  },
  {
   "en": "Streetwise",
   "ru": "Уроки улиц",
   "q": 0,
   "owner": "Нея Карлссон",
   "icon": "survivorPerks/Nea Karlsson/Streetwise.png",
   "role": "s"
  },
  {
   "en": "Boil Over",
   "ru": "Через край",
   "q": 0,
   "owner": "Кейт Денсон",
   "icon": "survivorPerks/Kate Denson/Boil Over.png",
   "role": "s"
  },
  {
   "en": "Come and Get Me!",
   "ru": "Эй, я здесь!",
   "q": 0,
   "owner": "Рик Граймс",
   "icon": "survivorPerks/Rick Grimes/Come and Get Me!.png",
   "role": "s"
  },
  {
   "en": "Empathic Connection",
   "ru": "Эмпатическая связь",
   "q": 0,
   "owner": "Ёити Асакава",
   "icon": "survivorPerks/Yoichi Asakawa/Empathic Connection.png",
   "role": "s"
  },
  {
   "en": "This is Not Happening",
   "ru": "Этому не бывать",
   "q": 0,
   "owner": "Навык",
   "icon": "survivorPerks/General Survivor/This is Not Happening.png",
   "role": "s"
  },
  {
   "en": "Clairvoyance",
   "ru": "Ясновидение",
   "q": 0,
   "owner": "Микаэла Рид",
   "icon": "survivorPerks/Mikaela Reid/Clairvoyance.png",
   "role": "s"
  }
 ],
 "killerPerks": [
  {
   "en": "Corrupt Intervention",
   "ru": "ВМЕШАТЕЛЬСТВО СКВЕРНЫ",
   "q": 2,
   "owner": "ЧУМА",
   "icon": "killerPerks/Plague/Corrupt Intervention.png",
   "role": "k"
  },
  {
   "en": "Dead Man's Switch",
   "ru": "АВАРИЙНАЯ КНОПКА",
   "q": 2,
   "owner": "СТРЕЛОК",
   "icon": "killerPerks/Deathslinger/Dead Man_s Switch.png",
   "role": "k"
  },
  {
   "en": "Human Greed",
   "ru": "АЛЧНОСТЬ",
   "q": 0,
   "owner": "ТЕМНЫЙ ВЛАСТЕЛИН",
   "icon": "killerPerks/Dark Lord/Human Greed.png",
   "role": "k"
  },
  {
   "en": "THWACK",
   "ru": "БАЦ!",
   "q": 0,
   "owner": "ТОРГОВКА ЧЕРЕПАМИ",
   "icon": "killerPerks/Skull Merchant/THWACK.png",
   "role": "k"
  },
  {
   "en": "BBQ and Chili",
   "ru": "БАРБЕКЮ И ЧИЛИ",
   "q": 2,
   "owner": "КАННИБАЛ",
   "icon": "killerPerks/Cannibal/BBQ and Chili.png",
   "role": "k"
  },
  {
   "en": "Batteries Included",
   "ru": "БАТАРЕЙКИ В КОМПЛЕКТЕ",
   "q": 0,
   "owner": "ХОРОШИЙ ПАРЕНЬ",
   "icon": "killerPerks/Good Guy/Batteries Included.png",
   "role": "k"
  },
  {
   "en": "No Quarter",
   "ru": "БЕЗ ПОЩАДЫ",
   "q": 0,
   "owner": "ЕГЕРЬ",
   "icon": "killerPerks/Houndmaster/No Quarter.png",
   "role": "k"
  },
  {
   "en": "Unrelenting",
   "ru": "БЕЗЖАЛОСТНЫЙ",
   "q": 0,
   "owner": "НАВЫК",
   "icon": "killerPerks/General Killer/Unrelenting.png",
   "role": "k"
  },
  {
   "en": "Merciless Storm",
   "ru": "БЕЗЖАЛОСТНЫЙ ШТОРМ",
   "q": 1,
   "owner": "ОНРЁ",
   "icon": "killerPerks/Onryo/Merciless Storm.png",
   "role": "k"
  },
  {
   "en": "Languid Touch",
   "ru": "БЕЗЖИЗНЕННОЕ КАСАНИЕ",
   "q": 1,
   "owner": "ЛИЧ",
   "icon": "killerPerks/Lich/Languid Touch.png",
   "role": "k"
  },
  {
   "en": "Mad Grit",
   "ru": "БЕЗУМНОЕ УПОРСТВО",
   "q": 0,
   "owner": "ЛЕГИОН",
   "icon": "killerPerks/Legion/Mad Grit.png",
   "role": "k"
  },
  {
   "en": "Silent Shadow",
   "ru": "БЕЗМОЛВНАЯ ТЕНЬ",
   "q": 0,
   "owner": "СЛЭШЕР",
   "icon": "killerPerks/Slasher/Silent Shadow.png",
   "role": "k"
  },
  {
   "en": "Wandering Eye",
   "ru": "БЛУЖДАЮЩИЙ ВЗГЛЯД",
   "q": 0,
   "owner": "КРАСУ",
   "icon": "killerPerks/Krasue/Wandering Eye.png",
   "role": "k"
  },
  {
   "en": "Rapid Brutality",
   "ru": "БЫСТРАЯ ЖЕСТОКОСТЬ",
   "q": 1,
   "owner": "КСЕНОМОРФ",
   "icon": "killerPerks/Xenomorph/Rapid Brutality.png",
   "role": "k"
  },
  {
   "en": "Dominance",
   "ru": "ВЛАДЫЧЕСТВО",
   "q": 0,
   "owner": "ТЕМНЫЙ ВЛАСТЕЛИН",
   "icon": "killerPerks/Dark Lord/Dominance.png",
   "role": "k"
  },
  {
   "en": "Dragon's Grip",
   "ru": "ДРАКОНЬЯ ХВАТКА",
   "q": 1,
   "owner": "МОР",
   "icon": "killerPerks/Blight/Dragon_s Grip.png",
   "role": "k"
  },
  {
   "en": "Friends Til the End",
   "ru": "ДРУЗЬЯ ДО ГРОБА",
   "q": 1,
   "owner": "ХОРОШИЙ ПАРЕНЬ",
   "icon": "killerPerks/Good Guy/Friends Til the End.png",
   "role": "k"
  },
  {
   "en": "Nemesis",
   "ru": "ВОЗМЕЗДИЕ",
   "q": 0,
   "owner": "ОНИ",
   "icon": "killerPerks/Oni/Nemesis.png",
   "role": "k"
  },
  {
   "en": "None Are Free",
   "ru": "ВСЕ НЕСВОБОДНЫ",
   "q": 0,
   "owner": "ГУЛЬ",
   "icon": "killerPerks/Ghoul/None Are Free.png",
   "role": "k"
  },
  {
   "en": "Make Your Choice",
   "ru": "ВЫБОР ЗА ТОБОЙ",
   "q": 0,
   "owner": "СВИНЬЯ",
   "icon": "killerPerks/Pig/Make Your Choice.png",
   "role": "k"
  },
  {
   "en": "Surge",
   "ru": "ВЫБРОС",
   "q": 2,
   "owner": "ДЕМОГОРГОН",
   "icon": "killerPerks/Demogorgon/Surge.png",
   "role": "k"
  },
  {
   "en": "Forced Hesitation",
   "ru": "ВЫНУЖДЕННАЯ НЕРЕШИТЕЛЬНОСТЬ",
   "q": 0,
   "owner": "СИНГУЛЯРНОСТЬ",
   "icon": "killerPerks/Singularity/Forced Hesitation.png",
   "role": "k"
  },
  {
   "en": "No Way Out",
   "ru": "ВЫХОДА НЕТ",
   "q": 2,
   "owner": "ТРЮКАЧ",
   "icon": "killerPerks/Trickster/No Way Out.png",
   "role": "k"
  },
  {
   "en": "Genetic Limits",
   "ru": "ГЕНЕТИЧЕСКИЕ ОГРАНИЧЕНИЯ",
   "q": 1,
   "owner": "СИНГУЛЯРНОСТЬ",
   "icon": "killerPerks/Singularity/Genetic Limits.png",
   "role": "k"
  },
  {
   "en": "Franklin's Demise",
   "ru": "ГИБЕЛЬ ФРАНКЛИНА",
   "q": 1,
   "owner": "КАННИБАЛ",
   "icon": "killerPerks/Cannibal/Franklin_s Demise.png",
   "role": "k"
  },
  {
   "en": "Ravenous",
   "ru": "ГОЛОД",
   "q": 0,
   "owner": "КРАСУ",
   "icon": "killerPerks/Krasue/Ravenous.png",
   "role": "k"
  },
  {
   "en": "Lightborn",
   "ru": "ДЕТИЩЕ СВЕТА",
   "q": 0,
   "owner": "ДЕРЕВЕНЩИНА",
   "icon": "killerPerks/Hillbilly/Lightborn.png",
   "role": "k"
  },
  {
   "en": "Shadowborn",
   "ru": "ДЕТИЩЕ ТЬМЫ",
   "q": 0,
   "owner": "ПРИЗРАК",
   "icon": "killerPerks/Wraith/Shadowborn.png",
   "role": "k"
  },
  {
   "en": "Coup de Grace",
   "ru": "ДОБИВАНИЕ",
   "q": 1,
   "owner": "БЛИЗНЕЦЫ",
   "icon": "killerPerks/Twins/Coup de Grace.png",
   "role": "k"
  },
  {
   "en": "Game Afoot",
   "ru": "ДОГОНЯЛКИ",
   "q": 0,
   "owner": "ТОРГОВКА ЧЕРЕПАМИ",
   "icon": "killerPerks/Skull Merchant/Game Afoot.png",
   "role": "k"
  },
  {
   "en": "Machine Learning",
   "ru": "МАШИННОЕ ОБУЧЕНИЕ",
   "q": 0,
   "owner": "СИНГУЛЯРНОСТЬ",
   "icon": "killerPerks/Singularity/Machine Learning.png",
   "role": "k"
  },
  {
   "en": "Iron Maiden",
   "ru": "ЖЕЛЕЗНАЯ ДЕВА",
   "q": 0,
   "owner": "ЛЕГИОН",
   "icon": "killerPerks/Legion/Iron Maiden.png",
   "role": "k"
  },
  {
   "en": "Cruel Limits",
   "ru": "ЖЕСТОКАЯ ИЗОЛЯЦИЯ",
   "q": 0,
   "owner": "ДЕМОГОРГОН",
   "icon": "killerPerks/Demogorgon/Cruel Limits.png",
   "role": "k"
  },
  {
   "en": "Infectious Fright",
   "ru": "ЗАРАЗИТЕЛЬНЫЙ УЖАС",
   "q": 1,
   "owner": "ЧУМА",
   "icon": "killerPerks/Plague/Infectious Fright.png",
   "role": "k"
  },
  {
   "en": "Brutal Strength",
   "ru": "ЗВЕРСКАЯ СИЛА",
   "q": 1,
   "owner": "ОХОТНИК",
   "icon": "killerPerks/Trapper/Brutal Strength.png",
   "role": "k"
  },
  {
   "en": "Gearhead",
   "ru": "ЗНАТОК ТЕХНИКИ",
   "q": 0,
   "owner": "СТРЕЛОК",
   "icon": "killerPerks/Deathslinger/Gearhead.png",
   "role": "k"
  },
  {
   "en": "A Nurse's Calling",
   "ru": "ЗОВ МЕДСЕСТРЫ",
   "q": 2,
   "owner": "МЕДСЕСТРА",
   "icon": "killerPerks/Nurse/A Nurse_s Calling.png",
   "role": "k"
  },
  {
   "en": "Nowhere to Hide",
   "ru": "ИМ НЕ УКРЫТЬСЯ",
   "q": 2,
   "owner": "РЫЦАРЬ",
   "icon": "killerPerks/Knight/Nowhere to Hide.png",
   "role": "k"
  },
  {
   "en": "Alien Instinct",
   "ru": "ИНСТИНКТ ЧУЖОГО",
   "q": 1,
   "owner": "КСЕНОМОРФ",
   "icon": "killerPerks/Xenomorph/Alien Instinct.png",
   "role": "k"
  },
  {
   "en": "Hysteria",
   "ru": "ИСТЕРИЯ",
   "q": 0,
   "owner": "НЕМЕЗИС",
   "icon": "killerPerks/Nemesis/Hysteria.png",
   "role": "k"
  },
  {
   "en": "Bloodhound",
   "ru": "ИЩЕЙКА",
   "q": 0,
   "owner": "ПРИЗРАК",
   "icon": "killerPerks/Wraith/Bloodhound.png",
   "role": "k"
  },
  {
   "en": "Coulrophobia",
   "ru": "КЛОУНОФОБИЯ",
   "q": 1,
   "owner": "КЛОУН",
   "icon": "killerPerks/Clown/Coulrophobia.png",
   "role": "k"
  },
  {
   "en": "Insidious",
   "ru": "КОВАРСТВО",
   "q": 0,
   "owner": "НАВЫК",
   "icon": "killerPerks/General Killer/Insidious.png",
   "role": "k"
  },
  {
   "en": "Blood Warden",
   "ru": "КРОВАВЫЙ СМОТРИТЕЛЬ",
   "q": 0,
   "owner": "КОШМАР",
   "icon": "killerPerks/Nightmare/Blood Warden.png",
   "role": "k"
  },
  {
   "en": "Superior Anatomy",
   "ru": "ЛУЧШАЯ АНАТОМИЯ",
   "q": 0,
   "owner": "КУКЛОВОД",
   "icon": "killerPerks/Mastermind/Superior Anatomy.png",
   "role": "k"
  },
  {
   "en": "Undone",
   "ru": "НЕЗАВЕРШЕННОЕ",
   "q": 0,
   "owner": "НЕВЕДОМОЕ",
   "icon": "killerPerks/Unknown/Undone.png",
   "role": "k"
  },
  {
   "en": "Rampage",
   "ru": "НЕИСТОВСТВО",
   "q": 0,
   "owner": "СЛЭШЕР",
   "icon": "killerPerks/Slasher/Rampage.png",
   "role": "k"
  },
  {
   "en": "Rancor",
   "ru": "НЕНАВИСТЬ",
   "q": 1,
   "owner": "ДУХ",
   "icon": "killerPerks/Spirit/Rancor.png",
   "role": "k"
  },
  {
   "en": "Haywire",
   "ru": "НЕПОЛАДКИ",
   "q": 0,
   "owner": "АНИМАТРОНИК",
   "icon": "killerPerks/Animatronic/Haywire.png",
   "role": "k"
  },
  {
   "en": "Unforeseen",
   "ru": "НЕПРЕДВИДЕННОЕ",
   "q": 1,
   "owner": "НЕВЕДОМОЕ",
   "icon": "killerPerks/Unknown/Unforeseen.png",
   "role": "k"
  },
  {
   "en": "Agitation",
   "ru": "НЕТЕРПИМОСТЬ",
   "q": 2,
   "owner": "ОХОТНИК",
   "icon": "killerPerks/Trapper/Agitation.png",
   "role": "k"
  },
  {
   "en": "Knock Out",
   "ru": "НОКАУТ",
   "q": 0,
   "owner": "КАННИБАЛ",
   "icon": "killerPerks/Cannibal/Knock Out.png",
   "role": "k"
  },
  {
   "en": "All-Shaking Thunder",
   "ru": "ОГЛУШИТЕЛЬНЫЙ ГРОМ",
   "q": 0,
   "owner": "ЕГЕРЬ",
   "icon": "killerPerks/Houndmaster/All-Shaking Thunder.png",
   "role": "k"
  },
  {
   "en": "Save the Best for Last",
   "ru": "ОСТАВЬТЕ ЛУЧШЕЕ НАПОСЛЕДОК",
   "q": 1,
   "owner": "ТЕНЬ",
   "icon": "killerPerks/Shape/Save the Best for Last.png",
   "role": "k"
  },
  {
   "en": "Iron Grasp",
   "ru": "МЕРТВАЯ ХВАТКА",
   "q": 0,
   "owner": "НАВЫК",
   "icon": "killerPerks/General Killer/Iron Grasp.png",
   "role": "k"
  },
  {
   "en": "Deadlock",
   "ru": "МЕРТВАЯ ХВАТКА",
   "q": 2,
   "owner": "СЕНОБИТ",
   "icon": "killerPerks/Cenobite/Deadlock.png",
   "role": "k"
  },
  {
   "en": "Grim Embrace",
   "ru": "МРАЧНЫЕ ОБЪЯТЬЯ",
   "q": 2,
   "owner": "ХУДОЖНИЦА",
   "icon": "killerPerks/Artist/Grim Embrace.png",
   "role": "k"
  },
  {
   "en": "Surveillance",
   "ru": "НАБЛЮДЕНИЕ",
   "q": 0,
   "owner": "СВИНЬЯ",
   "icon": "killerPerks/Pig/Surveillance.png",
   "role": "k"
  },
  {
   "en": "Sloppy Butcher",
   "ru": "НЕБРЕЖНЫЙ МЯСНИК",
   "q": 2,
   "owner": "НАВЫК",
   "icon": "killerPerks/General Killer/Sloppy Butcher.png",
   "role": "k"
  },
  {
   "en": "Overwhelming Presence",
   "ru": "НЕВЫНОСИМОЕ ПРИСУТСТВИЕ",
   "q": 1,
   "owner": "ДОКТОР",
   "icon": "killerPerks/Doctor/Overwhelming Presence.png",
   "role": "k"
  },
  {
   "en": "Hex: Blood Favor",
   "ru": "ПОРЧА: БЛАГОВОЛЕНИЕ КРОВИ",
   "q": 2,
   "owner": "МОР",
   "icon": "killerPerks/Blight/Hex Blood Favor.png",
   "role": "k"
  },
  {
   "en": "Hex: Wretched Fate",
   "ru": "ПОРЧА: ГОРЬКАЯ УЧАСТЬ",
   "q": 1,
   "owner": "ТЕМНЫЙ ВЛАСТЕЛИН",
   "icon": "killerPerks/Dark Lord/Hex Wretched Fate.png",
   "role": "k"
  },
  {
   "en": "Hex: Two Can Play",
   "ru": "ПОРЧА: ИГРА ДЛЯ ДВОИХ",
   "q": 0,
   "owner": "ХОРОШИЙ ПАРЕНЬ",
   "icon": "killerPerks/Good Guy/Hex Two Can Play.png",
   "role": "k"
  },
  {
   "en": "Hex: Plaything",
   "ru": "ПОРЧА: ИГРУШКА",
   "q": 1,
   "owner": "СЕНОБИТ",
   "icon": "killerPerks/Cenobite/Hex Plaything.png",
   "role": "k"
  },
  {
   "en": "Hex: Retribution",
   "ru": "ПОРЧА: КАРА",
   "q": 1,
   "owner": "СТРЕЛОК",
   "icon": "killerPerks/Deathslinger/Hex Retribution.png",
   "role": "k"
  },
  {
   "en": "Hex: Huntress Lullaby",
   "ru": "ПОРЧА: КОЛЫБЕЛЬНАЯ ОХОТНИЦЫ",
   "q": 0,
   "owner": "ОХОТНИЦА",
   "icon": "killerPerks/Huntress/Hex Huntress Lullaby.png",
   "role": "k"
  },
  {
   "en": "Hex: Crowd Control",
   "ru": "ПОРЧА: КОНТРОЛЬ ТОЛПЫ",
   "q": 1,
   "owner": "ТРЮКАЧ",
   "icon": "killerPerks/Trickster/Hex Crowd Control.png",
   "role": "k"
  },
  {
   "en": "Blood Echo",
   "ru": "ОТЗВУК КРОВИ",
   "q": 0,
   "owner": "ОНИ",
   "icon": "killerPerks/Oni/Blood Echo.png",
   "role": "k"
  },
  {
   "en": "Deerstalker",
   "ru": "ОХОТНИК НА ОЛЕНЕЙ",
   "q": 0,
   "owner": "НАВЫК",
   "icon": "killerPerks/General Killer/Deerstalker.png",
   "role": "k"
  },
  {
   "en": "Turn Back the Clock",
   "ru": "ПЕРЕВЕСТИ ЧАСЫ НАЗАД",
   "q": 2,
   "owner": "ПЕРВЫЙ",
   "icon": "killerPerks/First/Turn Back the Clock.png",
   "role": "k"
  },
  {
   "en": "Overcharge",
   "ru": "ПЕРЕГРУЗКА",
   "q": 0,
   "owner": "ДОКТОР",
   "icon": "killerPerks/Doctor/Overcharge.png",
   "role": "k"
  },
  {
   "en": "Forever Entwined",
   "ru": "ПЕРЕПЛЕТЕННЫЕ НАВСЕГДА",
   "q": 1,
   "owner": "ГУЛЬ",
   "icon": "killerPerks/Ghoul/Forever Entwined.png",
   "role": "k"
  },
  {
   "en": "Eruption",
   "ru": "ПОДРЫВ",
   "q": 2,
   "owner": "НЕМЕЗИС",
   "icon": "killerPerks/Nemesis/Eruption.png",
   "role": "k"
  },
  {
   "en": "Play With Your Food",
   "ru": "ПОИГРАТЬ СО СВОЕЙ ЖЕРТВОЙ",
   "q": 0,
   "owner": "ТЕНЬ",
   "icon": "killerPerks/Shape/Play With Your Food.png",
   "role": "k"
  },
  {
   "en": "Remember Me",
   "ru": "ПОМНИ МЕНЯ",
   "q": 1,
   "owner": "КОШМАР",
   "icon": "killerPerks/Nightmare/Remember Me.png",
   "role": "k"
  },
  {
   "en": "Forced Penance",
   "ru": "ПРИНУДИТЕЛЬНАЯ МЕРА",
   "q": 0,
   "owner": "ПАЛАЧ",
   "icon": "killerPerks/Executioner/Forced Penance.png",
   "role": "k"
  },
  {
   "en": "Oppression",
   "ru": "ПРИТЕСНЕНИЕ",
   "q": 1,
   "owner": "БЛИЗНЕЦЫ",
   "icon": "killerPerks/Twins/Oppression.png",
   "role": "k"
  },
  {
   "en": "Thrilling Tremors",
   "ru": "ПУГАЮЩАЯ ТРЯСКА",
   "q": 1,
   "owner": "ГОУСТ ФЕЙС",
   "icon": "killerPerks/Ghostface/Thrilling Tremors.png",
   "role": "k"
  },
  {
   "en": "Unnerving Presence",
   "ru": "ПУГАЮЩЕЕ ПРИСУТСТВИЕ",
   "q": 0,
   "owner": "ОХОТНИК",
   "icon": "killerPerks/Trapper/Unnerving Presence.png",
   "role": "k"
  },
  {
   "en": "Shattered Hope",
   "ru": "РАЗБИТЫЕ НАДЕЖДЫ",
   "q": 0,
   "owner": "НАВЫК",
   "icon": "killerPerks/General Killer/Shattered Hope.png",
   "role": "k"
  },
  {
   "en": "Awakened Awareness",
   "ru": "РАЗВИТАЯ ВНИМАТЕЛЬНОСТЬ",
   "q": 0,
   "owner": "КУКЛОВОД",
   "icon": "killerPerks/Mastermind/Awakened Awareness.png",
   "role": "k"
  },
  {
   "en": "Discordance",
   "ru": "РАЗЛАД",
   "q": 1,
   "owner": "ЛЕГИОН",
   "icon": "killerPerks/Legion/Discordance.png",
   "role": "k"
  },
  {
   "en": "Mindbreaker",
   "ru": "РАЗРУШИТЕЛЬ РАЗУМА",
   "q": 1,
   "owner": "ДЕМОГОРГОН",
   "icon": "killerPerks/Demogorgon/Mindbreaker.png",
   "role": "k"
  },
  {
   "en": "Dissolution",
   "ru": "РАСТВОРЕНИЕ",
   "q": 1,
   "owner": "ГРЯЗЬ",
   "icon": "killerPerks/Dredge/Dissolution.png",
   "role": "k"
  },
  {
   "en": "Bamboozle",
   "ru": "РОЗЫГРЫШ",
   "q": 1,
   "owner": "КЛОУН",
   "icon": "killerPerks/Clown/Bamboozle.png",
   "role": "k"
  },
  {
   "en": "Leverage",
   "ru": "РЫЧАГ ВЛИЯНИЯ",
   "q": 1,
   "owner": "ТОРГОВКА ЧЕРЕПАМИ",
   "icon": "killerPerks/Skull Merchant/Leverage.png",
   "role": "k"
  },
  {
   "en": "Hubris",
   "ru": "СВИРЕПАЯ ГОРДЫНЯ",
   "q": 0,
   "owner": "РЫЦАРЬ",
   "icon": "killerPerks/Knight/Hubris.png",
   "role": "k"
  },
  {
   "en": "Unbound",
   "ru": "СВОБОДНОЕ",
   "q": 0,
   "owner": "НЕВЕДОМОЕ",
   "icon": "killerPerks/Unknown/Unbound.png",
   "role": "k"
  },
  {
   "en": "Weave Attunement",
   "ru": "СВЯЗЬ С ПЛЕТЕНИЕМ",
   "q": 0,
   "owner": "ЛИЧ",
   "icon": "killerPerks/Lich/Weave Attunement.png",
   "role": "k"
  },
  {
   "en": "Secret Project",
   "ru": "СЕКРЕТНЫЙ ПРОЕКТ",
   "q": 2,
   "owner": "ПЕРВЫЙ",
   "icon": "killerPerks/First/Secret Project.png",
   "role": "k"
  },
  {
   "en": "Scourge Hook: Jagged Compass",
   "ru": "СЕКУЩИЙ КРЮК: ЩЕРБАТЫЙ КОМПАС",
   "q": 1,
   "owner": "ЕГЕРЬ",
   "icon": "killerPerks/Houndmaster/Scourge Hook Jagged Compass.png",
   "role": "k"
  },
  {
   "en": "Distressing",
   "ru": "СЕЮЩИЙ СТРАХ",
   "q": 0,
   "owner": "НАВЫК",
   "icon": "killerPerks/General Killer/Distressing.png",
   "role": "k"
  },
  {
   "en": "Hoarder",
   "ru": "СКОПИДОМ",
   "q": 0,
   "owner": "БЛИЗНЕЦЫ",
   "icon": "killerPerks/Twins/Hoarder.png",
   "role": "k"
  },
  {
   "en": "Furtive Chase",
   "ru": "СКРЫТНАЯ ПОГОНЯ",
   "q": 1,
   "owner": "ГОУСТ ФЕЙС",
   "icon": "killerPerks/Ghostface/Furtive Chase.png",
   "role": "k"
  },
  {
   "en": "Monitor and Abuse",
   "ru": "СЛЕЖКА И НАКАЗАНИЕ",
   "q": 0,
   "owner": "ДОКТОР",
   "icon": "killerPerks/Doctor/Monitor and Abuse.png",
   "role": "k"
  },
  {
   "en": "Deathbound",
   "ru": "СМЕРТЕЛЬНЫЕ УЗЫ",
   "q": 0,
   "owner": "ПАЛАЧ",
   "icon": "killerPerks/Executioner/Deathbound.png",
   "role": "k"
  },
  {
   "en": "Ultimate Weapon",
   "ru": "СОВЕРШЕННОЕ ОРУЖИЕ",
   "q": 1,
   "owner": "КСЕНОМОРФ",
   "icon": "killerPerks/Xenomorph/Ultimate Weapon.png",
   "role": "k"
  },
  {
   "en": "Call of Brine",
   "ru": "СОЛЕНОЕ МОРЕ",
   "q": 1,
   "owner": "ОНРЁ",
   "icon": "killerPerks/Onryo/Call of Brine.png",
   "role": "k"
  },
  {
   "en": "Enduring",
   "ru": "СТОЙКИЙ",
   "q": 1,
   "owner": "ДЕРЕВЕНЩИНА",
   "icon": "killerPerks/Hillbilly/Enduring.png",
   "role": "k"
  },
  {
   "en": "Stridor",
   "ru": "СТРИДОР",
   "q": 0,
   "owner": "МЕДСЕСТРА",
   "icon": "killerPerks/Nurse/Stridor.png",
   "role": "k"
  },
  {
   "en": "Scourge Hook: Floods of Rage",
   "ru": "СЕКУЩИЙ КРЮК: «ПУЧИНА ЯРОСТИ»",
   "q": 1,
   "owner": "ОНРЁ",
   "icon": "killerPerks/Onryo/Scourge Hook Floods of Rage.png",
   "role": "k"
  },
  {
   "en": "Scourge Hook: Gift of Pain",
   "ru": "СЕКУЩИЙ КРЮК: ДАР БОЛИ",
   "q": 1,
   "owner": "СЕНОБИТ",
   "icon": "killerPerks/Cenobite/Scourge Hook Gift of Pain.png",
   "role": "k"
  },
  {
   "en": "Scourge Hook: Pain Resonance",
   "ru": "СЕКУЩИЙ КРЮК: РЕЗОНАНС БОЛИ",
   "q": 2,
   "owner": "ХУДОЖНИЦА",
   "icon": "killerPerks/Artist/Scourge Hook Pain Resonance.png",
   "role": "k"
  },
  {
   "en": "Hangman's Trick",
   "ru": "СЕКУЩИЙ КРЮК: СЕКРЕТ ПАЛАЧА",
   "q": 1,
   "owner": "СВИНЬЯ",
   "icon": "killerPerks/Pig/Hangman_s Trick.png",
   "role": "k"
  },
  {
   "en": "Scourge Hook: Monstrous Shrine",
   "ru": "СЕКУЩИЙ КРЮК: ЧУДОВИЩНЫЙ ХРАМ",
   "q": 0,
   "owner": "НАВЫК",
   "icon": "killerPerks/General Killer/Scourge Hook Monstrous Shrine.png",
   "role": "k"
  },
  {
   "en": "Predator",
   "ru": "ХИЩНИК",
   "q": 1,
   "owner": "ПРИЗРАК",
   "icon": "killerPerks/Wraith/Predator.png",
   "role": "k"
  },
  {
   "en": "Spies from the Shadows",
   "ru": "СУМЕРЕЧНЫЕ ШПИОНЫ",
   "q": 0,
   "owner": "НАВЫК",
   "icon": "killerPerks/General Killer/Spies from the Shadows.png",
   "role": "k"
  },
  {
   "en": "Zanshin Tactics",
   "ru": "ТАКТИКА ЗАНСИН",
   "q": 1,
   "owner": "ОНИ",
   "icon": "killerPerks/Oni/Zanshin Tactics.png",
   "role": "k"
  },
  {
   "en": "Thanatophobia",
   "ru": "ТАНАТОФОБИЯ",
   "q": 0,
   "owner": "МЕДСЕСТРА",
   "icon": "killerPerks/Nurse/Thanatophobia.png",
   "role": "k"
  },
  {
   "en": "Dark Devotion",
   "ru": "ТЕМНАЯ ПРЕДАННОСТЬ",
   "q": 0,
   "owner": "ЧУМА",
   "icon": "killerPerks/Plague/Dark Devotion.png",
   "role": "k"
  },
  {
   "en": "Dark Arrogance",
   "ru": "ТЕМНОЕ ВЫСОКОМЕРИЕ",
   "q": 0,
   "owner": "ЛИЧ",
   "icon": "killerPerks/Lich/Dark Arrogance.png",
   "role": "k"
  },
  {
   "en": "Territorial Imperative",
   "ru": "ТЕРРИТОРИАЛЬНЫЙ ИМПЕРАТИВ",
   "q": 0,
   "owner": "ОХОТНИЦА",
   "icon": "killerPerks/Huntress/Territorial Imperative.png",
   "role": "k"
  },
  {
   "en": "Bitter Murmur",
   "ru": "ТИХИЙ ШОРОХ",
   "q": 0,
   "owner": "НАВЫК",
   "icon": "killerPerks/General Killer/Bitter Murmur.png",
   "role": "k"
  },
  {
   "en": "Septic Touch",
   "ru": "ТЛЕТВОРНОЕ КАСАНИЕ",
   "q": 0,
   "owner": "ГРЯЗЬ",
   "icon": "killerPerks/Dredge/Septic Touch.png",
   "role": "k"
  },
  {
   "en": "Help Wanted",
   "ru": "ТРЕБУЮТСЯ РАБОТНИКИ",
   "q": 0,
   "owner": "АНИМАТРОНИК",
   "icon": "killerPerks/Animatronic/Help Wanted.png",
   "role": "k"
  },
  {
   "en": "Trail of Torment",
   "ru": "ТРОПА ТЕРЗАНИЙ",
   "q": 0,
   "owner": "ПАЛАЧ",
   "icon": "killerPerks/Executioner/Trail of Torment.png",
   "role": "k"
  },
  {
   "en": "Dying Light",
   "ru": "УГАСАЮЩИЙ СВЕТ",
   "q": 0,
   "owner": "ТЕНЬ",
   "icon": "killerPerks/Shape/Dying Light.png",
   "role": "k"
  },
  {
   "en": "Tinkerer",
   "ru": "УМЕЛЕЦ",
   "q": 2,
   "owner": "ДЕРЕВЕНЩИНА",
   "icon": "killerPerks/Hillbilly/Tinkerer.png",
   "role": "k"
  },
  {
   "en": "Starstruck",
   "ru": "ФАНАТЕНИЕ",
   "q": 1,
   "owner": "ТРЮКАЧ",
   "icon": "killerPerks/Trickster/Starstruck.png",
   "role": "k"
  },
  {
   "en": "Phantom Fear",
   "ru": "ФАНТОМНЫЙ СТРАХ",
   "q": 1,
   "owner": "АНИМАТРОНИК",
   "icon": "killerPerks/Animatronic/Phantom Fear.png",
   "role": "k"
  },
  {
   "en": "Spirit Fury",
   "ru": "ЯРОСТЬ ДУХА",
   "q": 0,
   "owner": "ДУХ",
   "icon": "killerPerks/Spirit/Spirit Fury.png",
   "role": "k"
  },
  {
   "en": "Beast of Prey",
   "ru": "ХИЩНЫЙ ЗВЕРЬ",
   "q": 0,
   "owner": "ОХОТНИЦА",
   "icon": "killerPerks/Huntress/Beast of Prey.png",
   "role": "k"
  },
  {
   "en": "Pop Goes the Weasel",
   "ru": "ЧЕРТИК ИЗ ТАБАКЕРКИ",
   "q": 2,
   "owner": "КЛОУН",
   "icon": "killerPerks/Clown/Pop Goes the Weasel.png",
   "role": "k"
  },
  {
   "en": "I'm All Ears",
   "ru": "ЧУТКИЙ СЛУХ",
   "q": 0,
   "owner": "ГОУСТ ФЕЙС",
   "icon": "killerPerks/Ghostface/I_m All Ears.png",
   "role": "k"
  },
  {
   "en": "Whispers",
   "ru": "ШЕПОТЫ",
   "q": 0,
   "owner": "НАВЫК",
   "icon": "killerPerks/General Killer/Whispers.png",
   "role": "k"
  },
  {
   "en": "Darkness Revealed",
   "ru": "ЯВЛЕНИЕ МРАКА",
   "q": 0,
   "owner": "ГРЯЗЬ",
   "icon": "killerPerks/Dredge/Darkness Revealed.png",
   "role": "k"
  },
  {
   "en": "Fire Up",
   "ru": "ЯРКОЕ ПЛАМЯ",
   "q": 1,
   "owner": "КОШМАР",
   "icon": "killerPerks/Nightmare/Fire Up.png",
   "role": "k"
  },
  {
   "en": "Hex: Devour Hope",
   "ru": "ПОРЧА: ПОЖИРАНИЕ НАДЕЖДЫ",
   "q": 1,
   "owner": "ВЕДЬМА",
   "icon": "killerPerks/Hag/Hex Devour Hope.png",
   "role": "k"
  },
  {
   "en": "Hex: Ruin",
   "ru": "ПОРЧА: ПОГИБЕЛЬ",
   "q": 2,
   "owner": "ВЕДЬМА",
   "icon": "killerPerks/Hag/Hex Ruin.png",
   "role": "k"
  },
  {
   "en": "Hex: Third Seal",
   "ru": "ПОРЧА: ТРЕТЬЯ ПЕЧАТЬ",
   "q": 1,
   "owner": "ВЕДЬМА",
   "icon": "killerPerks/Hag/Hex Third Seal.png",
   "role": "k"
  },
  {
   "en": "Hex: No One Escapes Death",
   "ru": "ПОРЧА: НИКОМУ НЕ СКРЫТЬСЯ ОТ СМЕРТИ",
   "q": 2,
   "owner": "НАВЫК",
   "icon": "killerPerks/General Killer/Hex No One Escapes Death.png",
   "role": "k"
  },
  {
   "en": "Hex: Thrill of the Hunt",
   "ru": "ПОРЧА: РАДОСТЬ ОХОТЫ",
   "q": 2,
   "owner": "НАВЫК",
   "icon": "killerPerks/General Killer/Hex Thrill of the Hunt.png",
   "role": "k"
  },
  {
   "en": "Hex: Haunted Ground",
   "ru": "ПОРЧА: ПРОКЛЯТАЯ ЗЕМЛЯ",
   "q": 1,
   "owner": "ДУХ",
   "icon": "killerPerks/Spirit/Hex Haunted Ground.png",
   "role": "k"
  },
  {
   "en": "Hex: Undying",
   "ru": "ПОРЧА: НЕ-СМЕРТЬ",
   "q": 2,
   "owner": "МОР",
   "icon": "killerPerks/Blight/Hex Undying.png",
   "role": "k"
  },
  {
   "en": "Lethal Pursuer",
   "ru": "ПРЕСЛЕДОВАТЕЛЬ-УБИЙЦА",
   "q": 2,
   "owner": "НЕМЕЗИС",
   "icon": "killerPerks/Nemesis/Lethal Pursuer.png",
   "role": "k"
  },
  {
   "en": "Hex: Pentimento",
   "ru": "ПОРЧА: ПЕНТИМЕНТО",
   "q": 2,
   "owner": "ХУДОЖНИЦА",
   "icon": "killerPerks/Artist/Hex Pentimento.png",
   "role": "k"
  },
  {
   "en": "Terminus",
   "ru": "ПОСЛЕДНИЙ ЭТАП",
   "q": 1,
   "owner": "КУКЛОВОД",
   "icon": "killerPerks/Mastermind/Terminus.png",
   "role": "k"
  },
  {
   "en": "Hex: Face the Darkness",
   "ru": "ПОРЧА: ЛИК МРАКА",
   "q": 0,
   "owner": "РЫЦАРЬ",
   "icon": "killerPerks/Knight/Hex Face the Darkness.png",
   "role": "k"
  },
  {
   "en": "Hex: Nothing But Misery",
   "ru": "ПОРЧА: ТОЛЬКО ОТЧАЯНИЕ",
   "q": 0,
   "owner": "ГУЛЬ",
   "icon": "killerPerks/Ghoul/Hex Nothing But Misery.png",
   "role": "k"
  },
  {
   "en": "Hex: Overture of Doom",
   "ru": "ПОРЧА: ПРЕДВЕСТИЕ РОКА",
   "q": 0,
   "owner": "КРАСУ",
   "icon": "killerPerks/Krasue/Hex Overture of Doom.png",
   "role": "k"
  },
  {
   "en": "Hex: Hive Mind",
   "ru": "ПОРЧА: РАЗУМ УЛЬЯ",
   "q": 2,
   "owner": "ПЕРВЫЙ",
   "icon": "killerPerks/First/Hex Hive Mind.png",
   "role": "k"
  },
  {
   "en": "Hex: Scared to Death",
   "ru": "ПОРЧА: СМЕРТЕЛЬНЫЙ ИСПУГ",
   "q": 0,
   "owner": "СЛЭШЕР",
   "icon": "killerPerks/Slasher/Hex Scared to Death.png",
   "role": "k"
  }
 ],
 "survivors": [
  {
   "ru": "Дуайт Фэйрфилд",
   "en": "Dwight Fairfield",
   "icon": "../assets/dbd/survivorIcons/Dwight Fairfield.png"
  },
  {
   "ru": "Мэг Томас",
   "en": "Meg Thomas",
   "icon": "../assets/dbd/survivorIcons/Meg Thomas.png"
  },
  {
   "ru": "Клодетт Морель",
   "en": "Claudette Morel",
   "icon": "../assets/dbd/survivorIcons/Claudette Morel.png"
  },
  {
   "ru": "Джейк Парк",
   "en": "Jake Park",
   "icon": "../assets/dbd/survivorIcons/Jake Park.png"
  },
  {
   "ru": "Нея Карлссон",
   "en": "Nea Karlsson",
   "icon": "../assets/dbd/survivorIcons/Nea Karlsson.png"
  },
  {
   "ru": "Лори Строуд",
   "en": "Laurie Strode",
   "icon": "../assets/dbd/survivorIcons/Laurie Strode.png"
  },
  {
   "ru": "Эйс Висконти",
   "en": "Ace Visconti",
   "icon": "../assets/dbd/survivorIcons/Ace Visconti.png"
  },
  {
   "ru": "Уильям «Билл» Овербек",
   "en": "Bill Overbeck",
   "icon": "../assets/dbd/survivorIcons/Bill Overbeck.png"
  },
  {
   "ru": "Фенг Мин",
   "en": "Feng Min",
   "icon": "../assets/dbd/survivorIcons/Feng Min.png"
  },
  {
   "ru": "Дэвид Кинг",
   "en": "David King",
   "icon": "../assets/dbd/survivorIcons/David King.png"
  },
  {
   "ru": "Квентин Смит",
   "en": "Quentin Smith",
   "icon": "../assets/dbd/survivorIcons/Quentin Smith.png"
  },
  {
   "ru": "Детектив Тэпп",
   "en": "David Tapp",
   "icon": "../assets/dbd/survivorIcons/David Tapp.png"
  },
  {
   "ru": "Кейт Денсон",
   "en": "Kate Denson",
   "icon": "../assets/dbd/survivorIcons/Kate Denson.png"
  },
  {
   "ru": "Адам Фрэнсис",
   "en": "Adam Francis",
   "icon": "../assets/dbd/survivorIcons/Adam Francis.png"
  },
  {
   "ru": "Джефф Йохансен",
   "en": "Jeff Johansen",
   "icon": "../assets/dbd/survivorIcons/Jeff Johansen.png"
  },
  {
   "ru": "Джейн Ромеро",
   "en": "Jane Romero",
   "icon": "../assets/dbd/survivorIcons/Jane Romero.png"
  },
  {
   "ru": "Эшли Джей Уильямс",
   "en": "Ash Williams",
   "icon": "../assets/dbd/survivorIcons/Ash Williams.png"
  },
  {
   "ru": "Нэнси Уиллер",
   "en": "Nancy Wheeler",
   "icon": "../assets/dbd/survivorIcons/Nancy Wheeler.png"
  },
  {
   "ru": "Стив Харрингтон",
   "en": "Steve Harrington",
   "icon": "../assets/dbd/survivorIcons/Steve Harrington.png"
  },
  {
   "ru": "Юи Кимура",
   "en": "Yui Kimura",
   "icon": "../assets/dbd/survivorIcons/Yui Kimura.png"
  },
  {
   "ru": "Зарина Кассир",
   "en": "Zarina Kassir",
   "icon": "../assets/dbd/survivorIcons/Zarina Kassir.png"
  },
  {
   "ru": "Шерил Мейсон",
   "en": "Cheryl Mason",
   "icon": "../assets/dbd/survivorIcons/Cheryl Mason.png"
  },
  {
   "ru": "Феликс Рихтер",
   "en": "Felix Richter",
   "icon": "../assets/dbd/survivorIcons/Felix Richter.png"
  },
  {
   "ru": "Элоди Ракото",
   "en": "Elodie Rakoto",
   "icon": "../assets/dbd/survivorIcons/Elodie Rakoto.png"
  },
  {
   "ru": "Ли Юнчин",
   "en": "Yun-Jin Lee",
   "icon": "../assets/dbd/survivorIcons/Yun-Jin Lee.png"
  },
  {
   "ru": "Джилл Валентайн",
   "en": "Jill Valentine",
   "icon": "../assets/dbd/survivorIcons/Jill Valentine.png"
  },
  {
   "ru": "Леон С. Кеннеди",
   "en": "Leon S Kennedy",
   "icon": "../assets/dbd/survivorIcons/Leon S Kennedy.png"
  },
  {
   "ru": "Микаэла Рид",
   "en": "Mikaela Reid",
   "icon": "../assets/dbd/survivorIcons/Mikaela Reid.png"
  },
  {
   "ru": "Хонас Васкес",
   "en": "Jonah Vasquez",
   "icon": "../assets/dbd/survivorIcons/Jonah Vasquez.png"
  },
  {
   "ru": "Ёити Асакава",
   "en": "Yoichi Asakawa",
   "icon": "../assets/dbd/survivorIcons/Yoichi Asakawa.png"
  },
  {
   "ru": "Хэдди Каур",
   "en": "Haddie Kaur",
   "icon": "../assets/dbd/survivorIcons/Haddie Kaur.png"
  },
  {
   "ru": "Ада Вонг",
   "en": "Ada Wong",
   "icon": "../assets/dbd/survivorIcons/Ada Wong.png"
  },
  {
   "ru": "Ребекка Чемберс",
   "en": "Rebecca Chambers",
   "icon": "../assets/dbd/survivorIcons/Rebecca Chambers.png"
  },
  {
   "ru": "Витторио Тоскано",
   "en": "Vittorio Toscano",
   "icon": "../assets/dbd/survivorIcons/Vittorio Toscano.png"
  },
  {
   "ru": "Талита Лира",
   "en": "Thalita Lyra",
   "icon": "../assets/dbd/survivorIcons/Thalita Lyra.png"
  },
  {
   "ru": "Ренато Лира",
   "en": "Renato Lyra",
   "icon": "../assets/dbd/survivorIcons/Renato Lyra.png"
  },
  {
   "ru": "Габриэль Сома",
   "en": "Gabriel Soma",
   "icon": "../assets/dbd/survivorIcons/Gabriel Soma.png"
  },
  {
   "ru": "Николас Кейдж",
   "en": "Nicolas Cage",
   "icon": "../assets/dbd/survivorIcons/Nicolas Cage.png"
  },
  {
   "ru": "Эллен Рипли",
   "en": "Ellen Ripley",
   "icon": "../assets/dbd/survivorIcons/Ellen Ripley.png"
  },
  {
   "ru": "Алан Уэйк",
   "en": "Alan Wake",
   "icon": "../assets/dbd/survivorIcons/Alan Wake.png"
  },
  {
   "ru": "Сейбл Уорд",
   "en": "Sable Ward",
   "icon": "../assets/dbd/survivorIcons/Sable Ward.png"
  },
  {
   "ru": "Аэстри Язар",
   "en": "Aestri Yazar",
   "icon": "../assets/dbd/survivorIcons/Aestri Yazar.png"
  },
  {
   "ru": "Лара Крофт",
   "en": "Lara Croft",
   "icon": "../assets/dbd/survivorIcons/Lara Croft.png"
  },
  {
   "ru": "Тревор Бельмонт",
   "en": "Trevor Belmont",
   "icon": "../assets/dbd/survivorIcons/Trevor Belmont.png"
  },
  {
   "ru": "Тори Кейн",
   "en": "Taurie Cain",
   "icon": "../assets/dbd/survivorIcons/Taurie Cain.png"
  },
  {
   "ru": "Орела Роуз",
   "en": "Orela Rose",
   "icon": "../assets/dbd/survivorIcons/Orela Rose.png"
  },
  {
   "ru": "Рик Граймс",
   "en": "Rick Grimes",
   "icon": "../assets/dbd/survivorIcons/Rick Grimes.png"
  },
  {
   "ru": "Мишон Граймс",
   "en": "Michonne Grimes",
   "icon": "../assets/dbd/survivorIcons/Michonne Grimes.png"
  },
  {
   "ru": "Ви Бунясак",
   "en": "Vee Boonyasak",
   "icon": "../assets/dbd/survivorIcons/Vee Boonyasak.png"
  },
  {
   "ru": "Дастин Хендерсон",
   "en": "Dustin Henderson",
   "icon": "../assets/dbd/survivorIcons/Dustin Henderson.png"
  },
  {
   "ru": "Одиннадцать",
   "en": "Eleven",
   "icon": "../assets/dbd/survivorIcons/Eleven.png"
  },
  {
   "ru": "Квон Тхэён",
   "en": "Kwon Tae-young",
   "icon": "../assets/dbd/survivorIcons/Kwon Tae-young.png"
  },
  {
   "ru": "Шейн Виигваас",
   "en": "Shane Wiigwaas",
   "icon": "../assets/dbd/survivorIcons/Shane Wiigwaas.webp"
  }
 ],
 "killers": [
  {
   "ru": "ОХОТНИК",
   "en": "Trapper",
   "icon": "../assets/dbd/killerIcons/Trapper.png"
  },
  {
   "ru": "ПРИЗРАК",
   "en": "Wraith",
   "icon": "../assets/dbd/killerIcons/Wraith.png"
  },
  {
   "ru": "ДЕРЕВЕНЩИНА",
   "en": "Hillbilly",
   "icon": "../assets/dbd/killerIcons/Hillbilly.png"
  },
  {
   "ru": "МЕДСЕСТРА",
   "en": "Nurse",
   "icon": "../assets/dbd/killerIcons/Nurse.png"
  },
  {
   "ru": "ТЕНЬ",
   "en": "Shape",
   "icon": "../assets/dbd/killerIcons/Shape Variant.png"
  },
  {
   "ru": "ВЕДЬМА",
   "en": "Hag",
   "icon": "../assets/dbd/killerIcons/Hag.png"
  },
  {
   "ru": "ДОКТОР",
   "en": "Doctor",
   "icon": "../assets/dbd/killerIcons/Doctor.png"
  },
  {
   "ru": "ОХОТНИЦА",
   "en": "Huntress",
   "icon": "../assets/dbd/killerIcons/Huntress.png"
  },
  {
   "ru": "КАННИБАЛ",
   "en": "Cannibal",
   "icon": "../assets/dbd/killerIcons/Cannibal.png"
  },
  {
   "ru": "КОШМАР",
   "en": "Nightmare",
   "icon": "../assets/dbd/killerIcons/Nightmare.png"
  },
  {
   "ru": "СВИНЬЯ",
   "en": "Pig",
   "icon": "../assets/dbd/killerIcons/Pig.png"
  },
  {
   "ru": "КЛОУН",
   "en": "Clown",
   "icon": "../assets/dbd/killerIcons/Clown.png"
  },
  {
   "ru": "ДУХ",
   "en": "Spirit",
   "icon": "../assets/dbd/killerIcons/Spirit.png"
  },
  {
   "ru": "ЛЕГИОН",
   "en": "Legion",
   "icon": "../assets/dbd/killerIcons/Legion.png"
  },
  {
   "ru": "ЧУМА",
   "en": "Plague",
   "icon": "../assets/dbd/killerIcons/Plague.png"
  },
  {
   "ru": "ГОУСТ ФЕЙС",
   "en": "Ghostface",
   "icon": "../assets/dbd/killerIcons/Ghostface.png"
  },
  {
   "ru": "ДЕМОГОРГОН",
   "en": "Demogorgon",
   "icon": "../assets/dbd/killerIcons/Demogorgon.png"
  },
  {
   "ru": "ОНИ",
   "en": "Oni",
   "icon": "../assets/dbd/killerIcons/Oni.png"
  },
  {
   "ru": "СТРЕЛОК",
   "en": "Deathslinger",
   "icon": "../assets/dbd/killerIcons/Deathslinger.png"
  },
  {
   "ru": "ПАЛАЧ",
   "en": "Executioner",
   "icon": "../assets/dbd/killerIcons/Executioner.png"
  },
  {
   "ru": "МОР",
   "en": "Blight",
   "icon": "../assets/dbd/killerIcons/Blight.png"
  },
  {
   "ru": "БЛИЗНЕЦЫ",
   "en": "Twins",
   "icon": "../assets/dbd/killerIcons/Twins.png"
  },
  {
   "ru": "ТРЮКАЧ",
   "en": "Trickster",
   "icon": "../assets/dbd/killerIcons/Trickster.png"
  },
  {
   "ru": "НЕМЕЗИС",
   "en": "Nemesis",
   "icon": "../assets/dbd/killerIcons/Nemesis.png"
  },
  {
   "ru": "СЕНОБИТ",
   "en": "Cenobite",
   "icon": "../assets/dbd/killerIcons/Cenobite.png"
  },
  {
   "ru": "ХУДОЖНИЦА",
   "en": "Artist",
   "icon": "../assets/dbd/killerIcons/Artist.png"
  },
  {
   "ru": "ОНРЁ",
   "en": "Onryo",
   "icon": "../assets/dbd/killerIcons/Onryo.png"
  },
  {
   "ru": "ГРЯЗЬ",
   "en": "Dredge",
   "icon": "../assets/dbd/killerIcons/Dredge.png"
  },
  {
   "ru": "КУКЛОВОД",
   "en": "Mastermind",
   "icon": "../assets/dbd/killerIcons/Mastermind.png"
  },
  {
   "ru": "РЫЦАРЬ",
   "en": "Knight",
   "icon": "../assets/dbd/killerIcons/Knight.png"
  },
  {
   "ru": "ТОРГОВКА ЧЕРЕПАМИ",
   "en": "Skull Merchant",
   "icon": "../assets/dbd/killerIcons/Skull Merchant.png"
  },
  {
   "ru": "СИНГУЛЯРНОСТЬ",
   "en": "Singularity",
   "icon": "../assets/dbd/killerIcons/Singularity.png"
  },
  {
   "ru": "КСЕНОМОРФ",
   "en": "Xenomorph",
   "icon": "../assets/dbd/killerIcons/Xenomorph.png"
  },
  {
   "ru": "ХОРОШИЙ ПАРЕНЬ",
   "en": "Good Guy",
   "icon": "../assets/dbd/killerIcons/Good Guy.png"
  },
  {
   "ru": "НЕВЕДОМОЕ",
   "en": "Unknown",
   "icon": "../assets/dbd/killerIcons/Unknown.png"
  },
  {
   "ru": "ЛИЧ",
   "en": "Lich",
   "icon": "../assets/dbd/killerIcons/Lich.png"
  },
  {
   "ru": "ТЕМНЫЙ ВЛАСТЕЛИН",
   "en": "Dark Lord",
   "icon": "../assets/dbd/killerIcons/Dark Lord.png"
  },
  {
   "ru": "ЕГЕРЬ",
   "en": "Houndmaster",
   "icon": "../assets/dbd/killerIcons/Houndmaster.png"
  },
  {
   "ru": "ГУЛЬ",
   "en": "Ghoul",
   "icon": "../assets/dbd/killerIcons/Ghoul.png"
  },
  {
   "ru": "АНИМАТРОНИК",
   "en": "Animatronic",
   "icon": "../assets/dbd/killerIcons/Animatronic.png"
  },
  {
   "ru": "КРАСУ",
   "en": "Krasue",
   "icon": "../assets/dbd/killerIcons/Krasue.png"
  },
  {
   "ru": "ПЕРВЫЙ",
   "en": "First",
   "icon": "../assets/dbd/killerIcons/T_UI_K42_TheFirst_Portrait.png"
  },
  {
   "ru": "СЛЭШЕР",
   "en": "Slasher",
   "icon": "../assets/dbd/killerIcons/Slasher.png"
  }
 ]
};
