// AUTO-GENERATED by tools/generate_data.py — do not edit by hand.
window.SHOP_DATA = {
 "killerPerks": {
  "S": [
   {
    "name": "ИМ НЕ УКРЫТЬСЯ",
    "img": "killerShopSpecificKillerPerks/S tier/Nowhere to Hide.png"
   },
   {
    "name": "ЧЕРТИК ИЗ ТАБАКЕРКИ",
    "img": "killerShopSpecificKillerPerks/S tier/Pop Goes the Weasel.png"
   },
   {
    "name": "СЕКУЩИЙ КРЮК: РЕЗОНАНС БОЛИ",
    "img": "killerShopSpecificKillerPerks/S tier/Scourge Hook Pain Resonance.png"
   }
  ],
  "A": [
   {
    "name": "НЕТЕРПИМОСТЬ",
    "img": "killerShopSpecificKillerPerks/A tier/Agitation.png"
   },
   {
    "name": "ПРЕСЛЕДОВАТЕЛЬ-УБИЙЦА",
    "img": "killerShopSpecificKillerPerks/A tier/Lethal Pursuer.png"
   },
   {
    "name": "СЕКУЩИЙ КРЮК: «ПУЧИНА ЯРОСТИ»",
    "img": "killerShopSpecificKillerPerks/A tier/Scourge Hook Floods of Rage.png"
   },
   {
    "name": "ПЕРЕВЕСТИ ЧАСЫ НАЗАД",
    "img": "killerShopSpecificKillerPerks/A tier/Turn Back the Clock.png"
   }
  ],
  "B": [
   {
    "name": "БАРБЕКЮ И ЧИЛИ",
    "img": "killerShopSpecificKillerPerks/B tier/BBQ and Chili.png"
   },
   {
    "name": "СОЛЕНОЕ МОРЕ",
    "img": "killerShopSpecificKillerPerks/B tier/Call of Brine.png"
   },
   {
    "name": "ВМЕШАТЕЛЬСТВО СКВЕРНЫ",
    "img": "killerShopSpecificKillerPerks/B tier/Corrupt Intervention.png"
   },
   {
    "name": "АВАРИЙНАЯ КНОПКА",
    "img": "killerShopSpecificKillerPerks/B tier/Dead Man_s Switch.png"
   },
   {
    "name": "ПОДРЫВ",
    "img": "killerShopSpecificKillerPerks/B tier/Eruption.png"
   },
   {
    "name": "МРАЧНЫЕ ОБЪЯТЬЯ",
    "img": "killerShopSpecificKillerPerks/B tier/Grim Embrace.png"
   },
   {
    "name": "НИКАКИХ ЗАПРЕТОВ",
    "img": "killerShopSpecificKillerPerks/B tier/No Holds Barred.png"
   },
   {
    "name": "ХИЩНИК",
    "img": "killerShopSpecificKillerPerks/B tier/Predator.png"
   }
  ],
  "C": [
   {
    "name": "ИНСТИНКТ ЧУЖОГО",
    "img": "killerShopSpecificKillerPerks/C tier/Alien Instinct.png"
   },
   {
    "name": "ТИХИЙ ШОРОХ",
    "img": "killerShopSpecificKillerPerks/C tier/Bitter Murmur.png"
   },
   {
    "name": "ЯВЛЕНИЕ МРАКА",
    "img": "killerShopSpecificKillerPerks/C tier/Darkness Revealed.png"
   },
   {
    "name": "ОХОТНИК НА ОЛЕНЕЙ",
    "img": "killerShopSpecificKillerPerks/C tier/Deerstalker.png"
   },
   {
    "name": "РАЗЛАД",
    "img": "killerShopSpecificKillerPerks/C tier/Discordance.png"
   },
   {
    "name": "ДРАКОНЬЯ ХВАТКА",
    "img": "killerShopSpecificKillerPerks/C tier/Dragon_s Grip.png"
   },
   {
    "name": "УГАСАЮЩИЙ СВЕТ",
    "img": "killerShopSpecificKillerPerks/C tier/Dying Light.png"
   },
   {
    "name": "ДРУЗЬЯ ДО ГРОБА",
    "img": "killerShopSpecificKillerPerks/C tier/Friends Til the End.png"
   },
   {
    "name": "ЗНАТОК ТЕХНИКИ",
    "img": "killerShopSpecificKillerPerks/C tier/Gearhead.png"
   },
   {
    "name": "СЕКУЩИЙ КРЮК: СЕКРЕТ ПАЛАЧА",
    "img": "killerShopSpecificKillerPerks/C tier/Hangman_s Trick.png"
   },
   {
    "name": "ПОРЧА: ЛИК МРАКА",
    "img": "killerShopSpecificKillerPerks/C tier/Hex Face the Darkness.png"
   },
   {
    "name": "ПОРЧА: РАЗУМ УЛЬЯ",
    "img": "killerShopSpecificKillerPerks/C tier/Hex Hive Mind.png"
   },
   {
    "name": "ПОРЧА: КОЛЫБЕЛЬНАЯ ОХОТНИЦЫ",
    "img": "killerShopSpecificKillerPerks/C tier/Hex Huntress Lullaby.png"
   },
   {
    "name": "ЧУТКИЙ СЛУХ",
    "img": "killerShopSpecificKillerPerks/C tier/I_m All Ears.png"
   },
   {
    "name": "МЕРТВАЯ ХВАТКА",
    "img": "killerShopSpecificKillerPerks/C tier/Iron Grasp.png"
   },
   {
    "name": "ВЫБОР ЗА ТОБОЙ",
    "img": "killerShopSpecificKillerPerks/C tier/Make Your Choice.png"
   },
   {
    "name": "НЕВЫНОСИМОЕ ПРИСУТСТВИЕ",
    "img": "killerShopSpecificKillerPerks/C tier/Overwhelming Presence.png"
   },
   {
    "name": "ФАНТОМНЫЙ СТРАХ",
    "img": "killerShopSpecificKillerPerks/C tier/Phantom Fear.png"
   },
   {
    "name": "ВЫБРОС",
    "img": "killerShopSpecificKillerPerks/C tier/Surge.png"
   },
   {
    "name": "ТАНАТОФОБИЯ",
    "img": "killerShopSpecificKillerPerks/C tier/Thanatophobia.png"
   },
   {
    "name": "ПУГАЮЩАЯ ТРЯСКА",
    "img": "killerShopSpecificKillerPerks/C tier/Thrilling Tremors.png"
   },
   {
    "name": "СОВЕРШЕННОЕ ОРУЖИЕ",
    "img": "killerShopSpecificKillerPerks/C tier/Ultimate Weapon.png"
   },
   {
    "name": "БЛУЖДАЮЩИЙ ВЗГЛЯД",
    "img": "killerShopSpecificKillerPerks/C tier/Wandering Eye.png"
   },
   {
    "name": "ТАКТИКА ЗАНСИН",
    "img": "killerShopSpecificKillerPerks/C tier/Zanshin Tactics.png"
   }
  ],
  "D": [
   {
    "name": "ЗОВ МЕДСЕСТРЫ",
    "img": "killerShopSpecificKillerPerks/D tier/A Nurse_s Calling.png"
   },
   {
    "name": "ОГЛУШИТЕЛЬНЫЙ ГРОМ",
    "img": "killerShopSpecificKillerPerks/D tier/All-Shaking Thunder.png"
   },
   {
    "name": "РАЗВИТАЯ ВНИМАТЕЛЬНОСТЬ",
    "img": "killerShopSpecificKillerPerks/D tier/Awakened Awareness.png"
   },
   {
    "name": "ОТЗВУК КРОВИ",
    "img": "killerShopSpecificKillerPerks/D tier/Blood Echo.png"
   },
   {
    "name": "КРОВАВЫЙ СМОТРИТЕЛЬ",
    "img": "killerShopSpecificKillerPerks/D tier/Blood Warden.png"
   },
   {
    "name": "КЛОУНОФОБИЯ",
    "img": "killerShopSpecificKillerPerks/D tier/Coulrophobia.png"
   },
   {
    "name": "ЯРКОЕ ПЛАМЯ",
    "img": "killerShopSpecificKillerPerks/D tier/Fire Up.png"
   },
   {
    "name": "ПРИНУДИТЕЛЬНАЯ МЕРА",
    "img": "killerShopSpecificKillerPerks/D tier/Forced Penance.png"
   },
   {
    "name": "ПЕРЕПЛЕТЕННЫЕ НАВСЕГДА",
    "img": "killerShopSpecificKillerPerks/D tier/Forever Entwined.png"
   },
   {
    "name": "ГЕНЕТИЧЕСКИЕ ОГРАНИЧЕНИЯ",
    "img": "killerShopSpecificKillerPerks/D tier/Genetic Limits.png"
   },
   {
    "name": "НЕПОЛАДКИ",
    "img": "killerShopSpecificKillerPerks/D tier/Haywire.png"
   },
   {
    "name": "ПОРЧА: ПОЖИРАНИЕ НАДЕЖДЫ",
    "img": "killerShopSpecificKillerPerks/D tier/Hex Devour Hope.png"
   },
   {
    "name": "ПОРЧА: КАРА",
    "img": "killerShopSpecificKillerPerks/D tier/Hex Retribution.png"
   },
   {
    "name": "ПОРЧА: ПОГИБЕЛЬ",
    "img": "killerShopSpecificKillerPerks/D tier/Hex Ruin.png"
   },
   {
    "name": "ПОРЧА: НЕ-СМЕРТЬ",
    "img": "killerShopSpecificKillerPerks/D tier/Hex Undying.png"
   },
   {
    "name": "АЛЧНОСТЬ",
    "img": "killerShopSpecificKillerPerks/D tier/Human Greed.png"
   },
   {
    "name": "ЗАРАЗИТЕЛЬНЫЙ УЖАС",
    "img": "killerShopSpecificKillerPerks/D tier/Infectious Fright.png"
   },
   {
    "name": "ЖЕЛЕЗНАЯ ДЕВА",
    "img": "killerShopSpecificKillerPerks/D tier/Iron Maiden.png"
   },
   {
    "name": "БЕЗУМНОЕ УПОРСТВО",
    "img": "killerShopSpecificKillerPerks/D tier/Mad Grit.png"
   },
   {
    "name": "БЕЗЖАЛОСТНЫЙ ШТОРМ",
    "img": "killerShopSpecificKillerPerks/D tier/Merciless Storm.png"
   },
   {
    "name": "БЕЗ ПОЩАДЫ",
    "img": "killerShopSpecificKillerPerks/D tier/No Quarter.png"
   },
   {
    "name": "ВЫХОДА НЕТ",
    "img": "killerShopSpecificKillerPerks/D tier/No Way Out.png"
   },
   {
    "name": "ПРИТЕСНЕНИЕ",
    "img": "killerShopSpecificKillerPerks/D tier/Oppression.png"
   },
   {
    "name": "ПЕРЕГРУЗКА",
    "img": "killerShopSpecificKillerPerks/D tier/Overcharge.png"
   },
   {
    "name": "НЕНАВИСТЬ",
    "img": "killerShopSpecificKillerPerks/D tier/Rancor.png"
   },
   {
    "name": "ГОЛОД",
    "img": "killerShopSpecificKillerPerks/D tier/Ravenous.png"
   },
   {
    "name": "ПОМНИ МЕНЯ",
    "img": "killerShopSpecificKillerPerks/D tier/Remember Me.png"
   },
   {
    "name": "СЕКУЩИЙ КРЮК: ЧУДОВИЩНЫЙ ХРАМ",
    "img": "killerShopSpecificKillerPerks/D tier/Scourge Hook Monstrous Shrine.png"
   },
   {
    "name": "СЕКУЩИЙ КРЮК: ПЛАЧУЩИЕ РАНЫ",
    "img": "killerShopSpecificKillerPerks/D tier/Scourge Hook Weeping Wounds.png"
   },
   {
    "name": "ТЛЕТВОРНОЕ КАСАНИЕ",
    "img": "killerShopSpecificKillerPerks/D tier/Septic Touch.png"
   },
   {
    "name": "ДЕТИЩЕ ТЬМЫ",
    "img": "killerShopSpecificKillerPerks/D tier/Shadowborn.png"
   },
   {
    "name": "РАЗБИТЫЕ НАДЕЖДЫ",
    "img": "killerShopSpecificKillerPerks/D tier/Shattered Hope.png"
   },
   {
    "name": "БЕЗМОЛВНАЯ ТЕНЬ",
    "img": "killerShopSpecificKillerPerks/D tier/Silent Shadow.png"
   },
   {
    "name": "СУМЕРЕЧНЫЕ ШПИОНЫ",
    "img": "killerShopSpecificKillerPerks/D tier/Spies from the Shadows.png"
   },
   {
    "name": "ФАНАТЕНИЕ",
    "img": "killerShopSpecificKillerPerks/D tier/Starstruck.png"
   },
   {
    "name": "НАБЛЮДЕНИЕ",
    "img": "killerShopSpecificKillerPerks/D tier/Surveillance.png"
   },
   {
    "name": "БАЦ!",
    "img": "killerShopSpecificKillerPerks/D tier/THWACK.png"
   },
   {
    "name": "ПОСЛЕДНИЙ ЭТАП",
    "img": "killerShopSpecificKillerPerks/D tier/Terminus.png"
   },
   {
    "name": "УМЕЛЕЦ",
    "img": "killerShopSpecificKillerPerks/D tier/Tinkerer.png"
   },
   {
    "name": "НЕЗАВЕРШЕННОЕ",
    "img": "killerShopSpecificKillerPerks/D tier/Undone.png"
   }
  ],
  "F": [
   {
    "name": "РОЗЫГРЫШ",
    "img": "killerShopSpecificKillerPerks/F tier/Bamboozle.png"
   },
   {
    "name": "БАТАРЕЙКИ В КОМПЛЕКТЕ",
    "img": "killerShopSpecificKillerPerks/F tier/Batteries Included.png"
   },
   {
    "name": "ХИЩНЫЙ ЗВЕРЬ",
    "img": "killerShopSpecificKillerPerks/F tier/Beast of Prey.png"
   },
   {
    "name": "ИЩЕЙКА",
    "img": "killerShopSpecificKillerPerks/F tier/Bloodhound.png"
   },
   {
    "name": "ЗВЕРСКАЯ СИЛА",
    "img": "killerShopSpecificKillerPerks/F tier/Brutal Strength.png"
   },
   {
    "name": "ДОБИВАНИЕ",
    "img": "killerShopSpecificKillerPerks/F tier/Coup de Grace.png"
   },
   {
    "name": "ЖЕСТОКАЯ ИЗОЛЯЦИЯ",
    "img": "killerShopSpecificKillerPerks/F tier/Cruel Limits.png"
   },
   {
    "name": "ТЕМНОЕ ВЫСОКОМЕРИЕ",
    "img": "killerShopSpecificKillerPerks/F tier/Dark Arrogance.png"
   },
   {
    "name": "ТЕМНАЯ ПРЕДАННОСТЬ",
    "img": "killerShopSpecificKillerPerks/F tier/Dark Devotion.png"
   },
   {
    "name": "СМЕРТЕЛЬНЫЕ УЗЫ",
    "img": "killerShopSpecificKillerPerks/F tier/Deathbound.png"
   },
   {
    "name": "РАСТВОРЕНИЕ",
    "img": "killerShopSpecificKillerPerks/F tier/Dissolution.png"
   },
   {
    "name": "СЕЮЩИЙ СТРАХ",
    "img": "killerShopSpecificKillerPerks/F tier/Distressing.png"
   },
   {
    "name": "ВЛАДЫЧЕСТВО",
    "img": "killerShopSpecificKillerPerks/F tier/Dominance.png"
   },
   {
    "name": "СТОЙКИЙ",
    "img": "killerShopSpecificKillerPerks/F tier/Enduring.png"
   },
   {
    "name": "ВЫНУЖДЕННАЯ НЕРЕШИТЕЛЬНОСТЬ",
    "img": "killerShopSpecificKillerPerks/F tier/Forced Hesitation.png"
   },
   {
    "name": "ГИБЕЛЬ ФРАНКЛИНА",
    "img": "killerShopSpecificKillerPerks/F tier/Franklin_s Demise.png"
   },
   {
    "name": "СКРЫТНАЯ ПОГОНЯ",
    "img": "killerShopSpecificKillerPerks/F tier/Furtive Chase.png"
   },
   {
    "name": "ДОГОНЯЛКИ",
    "img": "killerShopSpecificKillerPerks/F tier/Game Afoot.png"
   },
   {
    "name": "ТРЕБУЮТСЯ РАБОТНИКИ",
    "img": "killerShopSpecificKillerPerks/F tier/Help Wanted.png"
   },
   {
    "name": "ПОРЧА: БЛАГОВОЛЕНИЕ КРОВИ",
    "img": "killerShopSpecificKillerPerks/F tier/Hex Blood Favor.png"
   },
   {
    "name": "ПОРЧА: КОНТРОЛЬ ТОЛПЫ",
    "img": "killerShopSpecificKillerPerks/F tier/Hex Crowd Control.png"
   },
   {
    "name": "ПОРЧА: ШУТ ФОРТУНЫ",
    "img": "killerShopSpecificKillerPerks/F tier/Hex Fortune_s Fool.png"
   },
   {
    "name": "ПОРЧА: ПРОКЛЯТАЯ ЗЕМЛЯ",
    "img": "killerShopSpecificKillerPerks/F tier/Hex Haunted Ground.png"
   },
   {
    "name": "ПОРЧА: НИКОМУ НЕ СКРЫТЬСЯ ОТ СМЕРТИ",
    "img": "killerShopSpecificKillerPerks/F tier/Hex No One Escapes Death.png"
   },
   {
    "name": "ПОРЧА: ТОЛЬКО ОТЧАЯНИЕ",
    "img": "killerShopSpecificKillerPerks/F tier/Hex Nothing But Misery.png"
   },
   {
    "name": "ПОРЧА: ПРЕДВЕСТИЕ РОКА",
    "img": "killerShopSpecificKillerPerks/F tier/Hex Overture of Doom.png"
   },
   {
    "name": "ПОРЧА: ПЕНТИМЕНТО",
    "img": "killerShopSpecificKillerPerks/F tier/Hex Pentimento.png"
   },
   {
    "name": "ПОРЧА: СМЕРТЕЛЬНЫЙ ИСПУГ",
    "img": "killerShopSpecificKillerPerks/F tier/Hex Scared to Death.png"
   },
   {
    "name": "ПОРЧА: ТРЕТЬЯ ПЕЧАТЬ",
    "img": "killerShopSpecificKillerPerks/F tier/Hex Third Seal.png"
   },
   {
    "name": "ПОРЧА: РАДОСТЬ ОХОТЫ",
    "img": "killerShopSpecificKillerPerks/F tier/Hex Thrill of the Hunt.png"
   },
   {
    "name": "ПОРЧА: ИГРА ДЛЯ ДВОИХ",
    "img": "killerShopSpecificKillerPerks/F tier/Hex Two Can Play.png"
   },
   {
    "name": "ПОРЧА: ГОРЬКАЯ УЧАСТЬ",
    "img": "killerShopSpecificKillerPerks/F tier/Hex Wretched Fate.png"
   },
   {
    "name": "СКОПИДОМ",
    "img": "killerShopSpecificKillerPerks/F tier/Hoarder.png"
   },
   {
    "name": "СВИРЕПАЯ ГОРДЫНЯ",
    "img": "killerShopSpecificKillerPerks/F tier/Hubris.png"
   },
   {
    "name": "ИСТЕРИЯ",
    "img": "killerShopSpecificKillerPerks/F tier/Hysteria.png"
   },
   {
    "name": "КОВАРСТВО",
    "img": "killerShopSpecificKillerPerks/F tier/Insidious.png"
   },
   {
    "name": "НОКАУТ",
    "img": "killerShopSpecificKillerPerks/F tier/Knock Out.png"
   },
   {
    "name": "БЕЗЖИЗНЕННОЕ КАСАНИЕ",
    "img": "killerShopSpecificKillerPerks/F tier/Languid Touch.png"
   },
   {
    "name": "РЫЧАГ ВЛИЯНИЯ",
    "img": "killerShopSpecificKillerPerks/F tier/Leverage.png"
   },
   {
    "name": "ДЕТИЩЕ СВЕТА",
    "img": "killerShopSpecificKillerPerks/F tier/Lightborn.png"
   },
   {
    "name": "МАШИННОЕ ОБУЧЕНИЕ",
    "img": "killerShopSpecificKillerPerks/F tier/Machine Learning.png"
   },
   {
    "name": "РАЗРУШИТЕЛЬ РАЗУМА",
    "img": "killerShopSpecificKillerPerks/F tier/Mindbreaker.png"
   },
   {
    "name": "СЛЕЖКА И НАКАЗАНИЕ",
    "img": "killerShopSpecificKillerPerks/F tier/Monitor and Abuse.png"
   },
   {
    "name": "ВОЗМЕЗДИЕ",
    "img": "killerShopSpecificKillerPerks/F tier/Nemesis (1).png"
   },
   {
    "name": "ВСЕ НЕСВОБОДНЫ",
    "img": "killerShopSpecificKillerPerks/F tier/None Are Free.png"
   },
   {
    "name": "ПОИГРАТЬ СО СВОЕЙ ЖЕРТВОЙ",
    "img": "killerShopSpecificKillerPerks/F tier/Play With Your Food.png"
   },
   {
    "name": "НЕИСТОВСТВО",
    "img": "killerShopSpecificKillerPerks/F tier/Rampage.png"
   },
   {
    "name": "БЫСТРАЯ ЖЕСТОКОСТЬ",
    "img": "killerShopSpecificKillerPerks/F tier/Rapid Brutality.png"
   },
   {
    "name": "ОСТАВЬТЕ ЛУЧШЕЕ НАПОСЛЕДОК",
    "img": "killerShopSpecificKillerPerks/F tier/Save the Best for Last.png"
   },
   {
    "name": "СЕКУЩИЙ КРЮК: ЩЕРБАТЫЙ КОМПАС",
    "img": "killerShopSpecificKillerPerks/F tier/Scourge Hook Jagged Compass.png"
   },
   {
    "name": "СЕКРЕТНЫЙ ПРОЕКТ",
    "img": "killerShopSpecificKillerPerks/F tier/Secret Project.png"
   },
   {
    "name": "НЕБРЕЖНЫЙ МЯСНИК",
    "img": "killerShopSpecificKillerPerks/F tier/Sloppy Butcher.png"
   },
   {
    "name": "ЯРОСТЬ ДУХА",
    "img": "killerShopSpecificKillerPerks/F tier/Spirit Fury.png"
   },
   {
    "name": "СТРИДОР",
    "img": "killerShopSpecificKillerPerks/F tier/Stridor.png"
   },
   {
    "name": "ЛУЧШАЯ АНАТОМИЯ",
    "img": "killerShopSpecificKillerPerks/F tier/Superior Anatomy.png"
   },
   {
    "name": "ТЕРРИТОРИАЛЬНЫЙ ИМПЕРАТИВ",
    "img": "killerShopSpecificKillerPerks/F tier/Territorial Imperative.png"
   },
   {
    "name": "ТРОПА ТЕРЗАНИЙ",
    "img": "killerShopSpecificKillerPerks/F tier/Trail of Torment.png"
   },
   {
    "name": "СВОБОДНОЕ",
    "img": "killerShopSpecificKillerPerks/F tier/Unbound.png"
   },
   {
    "name": "НЕПРЕДВИДЕННОЕ",
    "img": "killerShopSpecificKillerPerks/F tier/Unforeseen.png"
   },
   {
    "name": "ПУГАЮЩЕЕ ПРИСУТСТВИЕ",
    "img": "killerShopSpecificKillerPerks/F tier/Unnerving Presence.png"
   },
   {
    "name": "БЕЗЖАЛОСТНЫЙ",
    "img": "killerShopSpecificKillerPerks/F tier/Unrelenting.png"
   },
   {
    "name": "СВЯЗЬ С ПЛЕТЕНИЕМ",
    "img": "killerShopSpecificKillerPerks/F tier/Weave Attunement.png"
   },
   {
    "name": "ШЕПОТЫ",
    "img": "killerShopSpecificKillerPerks/F tier/Whispers.png"
   }
  ]
 },
 "survivorPerks": {
  "0": [
   {
    "name": "Без сожаления",
    "desc": "В начале матча вы получаете ранение, а затем:\n• вы получаете эффект «Ослабление»;\n• ваши стоны от боли звучат на 100% тише;\n• вы не оставляете лужи крови;\n• вы восстанавливаетесь на 25% быстрее;\n• вы можете полностью восстановиться.",
    "img": "../assets/dbd/survivorPerks/Tier0/No Mither.png"
   }
  ],
  "1": [
   {
    "name": "Любыми средствами",
    "desc": "Рядом с упавшей доской удерживайте E 3 сек., чтобы вернуть ее на место.\n\nВы видите ауры упавших досок.",
    "img": "../assets/dbd/survivorPerks/Tier1/Any Means Necessary.png"
   },
   {
    "name": "Нянька",
    "desc": "Когда вы снимаете выжившего с крюка:\n• он получает 10% эффекта «Спешка» на 30 сек.;\n• он не оставляет пятна крови в течение 30 сек.;\n• не оставляет следы-трещины в течение 30 сек.;\n• вы видите ауру убийцы на протяжении 8 сек.",
    "img": "../assets/dbd/survivorPerks/Tier1/Babysitter.png"
   },
   {
    "name": "Бада-бада-бум",
    "desc": "После починки 20% генераторов, нажмите F возле окна, чтобы установить ловушку, действующую 60 сек. В течение этого времени все выжившие видят ауру этого окна.\n\nЕсли убийца выпрыгнет в это окно, ловушка взорвется и наложит на него 50% эффекта «Замедление» на 4 сек.",
    "img": "../assets/dbd/survivorPerks/Tier1/Bada Bada Boom.png"
   },
   {
    "name": "Вдохновение барда",
    "desc": "Если вы бездействуете, нажмите E, чтобы начать выступление, приободряя всех выживших в радиусе 16 м. Максимальная продолжительность: 15 сек. Пока вы выступаете, остальные выжившие видят вашу ауру.\nБросьте d20:\n• 1 | Вы кричите, но ничего не происходит.\n• 2-10 | Базовые проверки реакции дают +1% прогресса.\n• 11-19 | Базовые проверки реакции дают +2% прогресса.\n• 20 | Базовые проверки реакции дают +3% прогресса.\n\nЕсли вы завершите выступление, эффект сохранится еще на 90 сек. Перезарядка: 90 сек.",
    "img": "../assets/dbd/survivorPerks/Tier1/Bardic Inspiration.png"
   },
   {
    "name": "Фугасная мина",
    "desc": "После починки 40% генераторов нажмите F рядом с генератором, чтобы поставить на него ловушку, которая останется на 120 сек. Пока она действует, все выжившие видят ауру этого генератора.\n\nКогда убийца повреждает этот генератор, ловушка взрывается и:\n• оглушает убийцу на 4 сек.;\n• все, кто смотрел на взрыв, слепнут.",
    "img": "../assets/dbd/survivorPerks/Tier1/Blast Mine.png"
   },
   {
    "name": "Выше головы",
    "desc": "Если вас снимают с крюка до завершения ремонта всех генераторов, в течение 60 сек., пока на вас действует эффект «Усталость», нажмите E, чтобы мгновенно избавиться от эффекта «Усталость».\n\nДействия, привлекающие внимание, отменяют этот эффект.",
    "img": "../assets/dbd/survivorPerks/Tier1/Blood Rush.png"
   },
   {
    "name": "Через край",
    "desc": "Пока убийца вас несет:\n• когда убийца падает с высоты не менее 1.2 м, попытки вырваться приносят на 33% больше прогресса;\n• вы вырываетесь на 80% сильнее;\n• убийца не видит ауры крюков в радиусе 16 м.",
    "img": "../assets/dbd/survivorPerks/Tier1/Boil Over.png"
   },
   {
    "name": "Дар: Экспонента",
    "desc": "Когда вы стоите рядом с тотемом, нажмите E, чтобы благословить его и создать уникальный дарующий тотем со всеми вашими дарами.\n\nСмертельно раненые выжившие в радиусе действия этого тотема:\n• восстанавливаются на 100% быстрее;\n• могут восстановиться полностью.",
    "img": "../assets/dbd/survivorPerks/Tier1/Boon Exponential.png"
   },
   {
    "name": "Дар: Уход в тень",
    "desc": "Когда вы стоите рядом с тотемом, нажмите E, чтобы благословить его и создать уникальный дарующий тотем со всеми вашими дарами. Выжившие в радиусе действия этого тотема:\n• не оставляют следы-трещины;\n• убийца не может видеть их ауры.\n\nПосле выхода из этой области эффект сохраняется еще 4 сек.",
    "img": "../assets/dbd/survivorPerks/Tier1/Boon Shadow Step.png"
   },
   {
    "name": "Поломка",
    "desc": "Когда вас снимают с крюка:\n• крюк ломается, затем чинится через 180 сек.;\n• вы видите ауру убийцы в течение 6 сек.",
    "img": "../assets/dbd/survivorPerks/Tier1/Breakdown.png"
   },
   {
    "name": "Форсаж",
    "desc": "Когда вы находитесь в пределах 5 м от выжившего, которого несут:\n• вы получаете 10% эффекта «Спешка»;\n• выживший, которого несут, вырывается на 25% быстрее.",
    "img": "../assets/dbd/survivorPerks/Tier1/Breakout.png"
   },
   {
    "name": "Строим на века",
    "desc": "Если вы прятались в шкафчике в течение 10 сек., держа в руках полностью разряженный предмет, он восстанавливает 99% заряда.\n\nПри каждой повторной подобной перезарядке, зарядов восстанавливается на 33% меньше.",
    "img": "../assets/dbd/survivorPerks/Tier1/Built to Last.png"
   },
   {
    "name": "Товарищество",
    "desc": "Пока вы боретесь на крюке, а другой выживший находится в пределах 16 м, таймер приостанавливается на 34 сек.",
    "img": "../assets/dbd/survivorPerks/Tier1/Camaraderie.png"
   },
   {
    "name": "Воин света",
    "desc": "Если вы используете фонарик, то получаете 50% эффекта «Спешка».\n\nКогда вы ослепляете убийцу, он получает 20% эффекта «Замедление» на 6 сек. Перезарядка: 40 сек.",
    "img": "../assets/dbd/survivorPerks/Tier1/Champion of Light.png"
   },
   {
    "name": "Химическая ловушка",
    "desc": "После починки 20% генераторов, нажмите F возле упавшей доски, чтобы установить ловушку, действующую 60 сек. В течение этого времени все выжившие видят ауру этой доски.\n\nЕсли убийца сломает эту доску, ловушка взорвется и наложит на него 50% эффекта «Замедление» на 4 сек.",
    "img": "../assets/dbd/survivorPerks/Tier1/Chemical Trap.png"
   },
   {
    "name": "Убежденность",
    "desc": "После 1-го исцеления других выживших, если вы смертельно ранены и прогресс восстановления достиг 25%, нажмите E, чтобы восстановиться мгновенно.\n\nВы получите эффект «Ослабление», а через 30 сек. снова будете смертельно ранены.",
    "img": "../assets/dbd/survivorPerks/Tier1/Conviction.png"
   },
   {
    "name": "Уловка",
    "desc": "Каждый раз, когда вы пытаетесь быстро войти в шкафчик:\n• вы не входите в шкафчик;\n• убийца получает оповещение;\n• вы не оставляете следы-трещины в течение 5 сек.\n\nПерезарядка: 15 сек.",
    "img": "../assets/dbd/survivorPerks/Tier1/Deception.png"
   },
   {
    "name": "Отчаянные меры",
    "desc": "За каждого раненого, смертельно раненого или повешенного на крюк выжившего:\n• вы исцеляетесь на 20% быстрее;\n• слезаете с крюка на 20% быстрее.",
    "img": "../assets/dbd/survivorPerks/Tier1/Desperate Measures.png"
   },
   {
    "name": "Детективное чутье",
    "desc": "Когда завершается ремонт генератора, вы в течение 20 сек. на расстоянии в 64 м:\n• видите ауры сундуков;\n• видите в течение ауры генераторов;\n• видите ауры тотемов.",
    "img": "../assets/dbd/survivorPerks/Tier1/Detective_s Hunch.png"
   },
   {
    "name": "Диверсия",
    "desc": "Когда вы в течение 20 сек., пригнувшись и бездействуя, прячетесь в радиусе террора убийцы, используйте E, чтобы бросить камешек на 20 м, который:\n• привлечет внимание убийцы;\n• оставит следы-трещины.",
    "img": "../assets/dbd/survivorPerks/Tier1/Diversion.png"
   },
   {
    "name": "Не навреди",
    "desc": "Во время лечения другого выжившего:\n• за каждую его стадию крюка ваша скорость исцеления возрастает на 50%;\n• за отличную базовую проверку реакции вы получаете на 3% больше прогресса.",
    "img": "../assets/dbd/survivorPerks/Tier1/Do No Harm.png"
   },
   {
    "name": "Эмпатическая связь",
    "desc": "Вы лечите товарищей на 35% быстрее.\n\nРаненые выжившие видят вашу ауру.",
    "img": "../assets/dbd/survivorPerks/Tier1/Empathic Connection.png"
   },
   {
    "name": "Световая граната",
    "desc": "После починки 40% генераторов, когда вы прячетесь в шкафчике, нажмите E, чтобы изготовить световую гранату.\n\nПри использовании она:\n• ослепляет всех, кто смотрит на взрыв;\n• привлекает внимание убийцы.",
    "img": "../assets/dbd/survivorPerks/Tier1/Flashbang.png"
   },
   {
    "name": "Дружеское состязание",
    "desc": "Когда вы чините генератор совместно с выжившим, по завершении ремонта выжившие, участвовавшие в этом процессе, начинают чинить на 5% быстрее в течение 120 сек.",
    "img": "../assets/dbd/survivorPerks/Tier1/Friendly Competition.png"
   },
   {
    "name": "Внутренняя сила",
    "desc": "Если вы очистили тотем, а позже просидели в шкафчике не менее 8 сек. с ранением и без эффекта «Ослабление», вы полностью исцеляетесь.",
    "img": "../assets/dbd/survivorPerks/Tier1/Inner Strength.png"
   },
   {
    "name": "Последний рубеж",
    "desc": "Если вы прячетесь в радиусе террора убийцы в течение 90 сек., то один раз за матч можете оглушить убийцу быстрым прыжком на 3 сек., если он окажется в радиусе 2.5 м.",
    "img": "../assets/dbd/survivorPerks/Tier1/Last Stand.png"
   },
   {
    "name": "Ниже травы",
    "desc": "Если все остальные выжившие смертельно ранены или подвешены, в течение 90 сек. вы:\n• не стонете от боли;\n• не оставляете лужи крови;\n• не оставляете следы-трещины.",
    "img": "../assets/dbd/survivorPerks/Tier1/Low Profile.png"
   },
   {
    "name": "Призвание",
    "desc": "Если вы ранены и заканчиваете лечение другого выжившего, то получаете эффект «Стойкость» на 10 сек.\n\nЕсли у вас глубокая рана, вы получаете 3% эффекта «Спешка».",
    "img": "../assets/dbd/survivorPerks/Tier1/Made For This.png"
   },
   {
    "name": "Зеркальная иллюзия",
    "desc": "После починки 20% генераторов, стоя у сундука, рубильника ворот, генератора или тотема, нажмите F, чтобы создать статичную иллюзию на 60 сек.",
    "img": "../assets/dbd/survivorPerks/Tier1/Mirrored Illusion.png"
   },
   {
    "name": "Мародерское чутье",
    "desc": "Вы видите ауры запертых сундуков и упавших предметов в радиусе 64 м.\n\nКогда вы открываете сундук, вероятность найти редкий предмет возрастает на 50%.",
    "img": "../assets/dbd/survivorPerks/Tier1/Plunderer_s Instinct.png"
   },
   {
    "name": "Потенциальная энергия",
    "desc": "Во время починки нажмите F, чтобы получить жетоны вместо прогресса (до 20 шт.).\n\nЕсли у вас есть хотя бы 1 шт. жетонов, нажмите F, чтобы истратить их все и получить 1% прогресса за каждый.\n\nЕсли вы получаете урон, все жетоны теряются.",
    "img": "../assets/dbd/survivorPerks/Tier1/Potential Energy.png"
   },
   {
    "name": "Быстрый и тихий",
    "desc": "Вы бесшумно прячетесь в ящиках и прыгаете. Убийца не оповещается. Перезарядка: 15 сек.",
    "img": "../assets/dbd/survivorPerks/Tier1/Quick and Quiet.png"
   },
   {
    "name": "Обман во благо",
    "desc": "Когда чините генератор не менее 1 сек., вы видите его ауру.\n\nКогда вы прячетесь в шкафчике, убийца получает оповещение о генераторе. Перезарядка: 15 сек.",
    "img": "../assets/dbd/survivorPerks/Tier1/Red Herring.png"
   },
   {
    "name": "Скрытый союз",
    "desc": "Если вы в одиночку ремонтируете генераторы в течение 45 сек., нажмите E, чтобы заблокировать генератор на 30 сек.",
    "img": "../assets/dbd/survivorPerks/Tier1/Repressed Alliance.png"
   },
   {
    "name": "Остаточное проявление",
    "desc": "Когда вы ослепляете убийцу, он получает эффект «Слепота» на 30 сек.\n\nВы можете обыскать сундук 1 раз(а). При первом обыске в сундуке вы найдете необычный фонарик.",
    "img": "../assets/dbd/survivorPerks/Tier1/Residual Manifest.png"
   },
   {
    "name": "Крушитель",
    "desc": "В пределах 56 м от места, где убийца поднял и понес выжившего, вы видите ауры обычных и секущих крюков.\n\nВы можете ломать крюки. Перезарядка: 60 сек.",
    "img": "../assets/dbd/survivorPerks/Tier1/Saboteur.png"
   },
   {
    "name": "Сам себе доктор",
    "desc": "Вы лечите себя со скоростью 35%.",
    "img": "../assets/dbd/survivorPerks/Tier1/Self Care.png"
   },
   {
    "name": "Солидарность",
    "desc": "Когда вы ранены и лечите другого выжившего без аптечки, вы также лечитесь со скоростью 70%.",
    "img": "../assets/dbd/survivorPerks/Tier1/Solidarity.png"
   },
   {
    "name": "Оберег души",
    "desc": "Вы можете восстановиться полностью, пока прокляты.\n\nЕсли вы полностью восстанавливаетесь, то получаете эффект «Стойкость» на 8 сек. Перезарядка 30 сек.",
    "img": "../assets/dbd/survivorPerks/Tier1/Soul Guard.png"
   },
   {
    "name": "Сила во мраке",
    "desc": "Если вы ранены и находитесь в подвале, то:\n• можете исцелить себя со скоростью 70%.\n• Завершая лечение, вы видите ауру убийцы в течение 10 сек.",
    "img": "../assets/dbd/survivorPerks/Tier1/Strength in Shadows.png"
   },
   {
    "name": "Командная работа: Собраться с силами",
    "desc": "Когда другой выживший ослепляет или оглушает доской убийцу в пределах 24 м от вас, в течение 30 сек. вы:\n• не стонете от боли;\n• не оставляете лужи крови;\n• не оставляете следы-трещины.",
    "img": "../assets/dbd/survivorPerks/Tier1/Teamwork Toughen Up.png"
   },
   {
    "name": "Выдержка",
    "desc": "Когда смертельно ранены:\n• вы получаете 50% эффекта «Спешка»;\n• вы можете одновременно ползти и восстанавливаться;\n• ваши стоны от боли звучат на 75% тише.",
    "img": "../assets/dbd/survivorPerks/Tier1/Tenacity.png"
   },
   {
    "name": "Городской бег",
    "desc": "Вы получаете 100% эффекта «Спешка», когда пригнулись.",
    "img": "../assets/dbd/survivorPerks/Tier1/Urban Evasion.png"
   },
   {
    "name": "Визионер",
    "desc": "Вы видите ауры генераторов в радиусе 32 м.\n\nКогда ремонт генератора завершен, перезарядка: 16 сек.",
    "img": "../assets/dbd/survivorPerks/Tier1/Visionary.png"
   },
   {
    "name": "Проснись",
    "desc": "Когда завершается ремонт всех генераторов:\n• вы видите ауры рубильников ворот.\n• Когда вы открываете ворота, другие выжившие видят вашу ауру.\n• За каждого живого выжившего вы открываете ворота на 12.5% быстрее.",
    "img": "../assets/dbd/survivorPerks/Tier1/Wake Up.png"
   },
   {
    "name": "Жучок",
    "desc": "После починки 40% генераторов нажмите F рядом с генератором, чтобы установить ловушку, которая сохраняется 120 сек. или до тех пор, пока убийца не повредит генератор. В течение этого времени все выжившие видят ауру этого генератора.\n\nВсе выжившие видят ауру убийцы, пока тот находится в радиусе 14 м от этого генератора.",
    "img": "../assets/dbd/survivorPerks/Tier1/Wiretap.png"
   }
  ],
  "2": [
   {
    "name": "Самоучка",
    "desc": "Вы начинаете матч с жетонами (0 шт., максимум — 5), а ваши базовые проверки лечения приносят на 15% меньше прогресса.\n\nКогда вы лечитесь без аптечки:\n• проходя базовую проверку, вы получаете жетоны (1);\n• за каждый жетон при каждой базовой проверке ваш прогресс увеличивается еще на 15%;\n• отличные базовые проверки реакции недоступны.",
    "img": "../assets/dbd/survivorPerks/Tier2/Autodidact.png"
   },
   {
    "name": "Запасной игрок",
    "desc": "Когда убийца поднимает другого выжившего, если в течение 10 сек. вы побежите, то:\n• получите 50% эффекта «Спешка» на 5 сек.;\n• получите эффект «Усталость» на 20 сек.",
    "img": "../assets/dbd/survivorPerks/Tier2/Background Player.png"
   },
   {
    "name": "Дар: Круг исцеления",
    "desc": "Когда вы стоите рядом с тотемом, нажмите E, чтобы благословить его и создать уникальный дарующий тотем со всеми вашими дарами.\n\nВыжившие в радиусе этого тотема получают следующие эффекты:\n• во время лечения без аптечки они исцеляют товарищей на 100% быстрее;\n• когда они ранены, остальные выжившие видят их ауры.",
    "img": "../assets/dbd/survivorPerks/Tier2/Boon Circle of Healing.png"
   },
   {
    "name": "Познания в ботанике",
    "desc": "Скорость лечения увеличивается на 50%.",
    "img": "../assets/dbd/survivorPerks/Tier2/Botany Knowledge.png"
   },
   {
    "name": "С чистого листа",
    "desc": "Когда вы завершаете лечение другого выжившего, пока кто-то лечит вас, нажмите E, чтобы получить эффект «Ослабление».\n\nЕсли вы не получите смертельного ранения в течение 60 сек., то мгновенно исцелитесь.",
    "img": "../assets/dbd/survivorPerks/Tier2/Clean Break.png"
   },
   {
    "name": "Потанцуй со мной",
    "desc": "Быстро выбираясь из шкафчика или прыгая на средней или большой скорости через препятствие, вы не оставляете следы-трещины в течение 5 сек. Перезарядка: 15 сек.",
    "img": "../assets/dbd/survivorPerks/Tier2/Dance With Me.png"
   },
   {
    "name": "Врачебный долг",
    "desc": "Если вы здоровы и берете удар на себя, другие выжившие в радиусе 12 м получают 25% эффекта «Спешка» на 6 сек.",
    "img": "../assets/dbd/survivorPerks/Tier2/Duty Of Care.png"
   },
   {
    "name": "Сноровка",
    "desc": "Если вы здоровы, быстрые прыжки ускоряются на 20%.\n\nПосле быстрого прыжка перезарядка: 30 сек.",
    "img": "../assets/dbd/survivorPerks/Tier2/Finesse.png"
   },
   {
    "name": "На пять шагов впереди",
    "desc": "Если вы находитесь в радиусе террора убийцы или он преследует вас:\n• вы видите ауры ближайших досок и окон (5);\n• после опрокидывания доски вы начинаете двигаться на 50% раньше;\n• после опрокидывания доски начинается перезарядка: 30 сек.",
    "img": "../assets/dbd/survivorPerks/Tier2/Five Moves Ahead.png"
   },
   {
    "name": "Состояние потока",
    "desc": "При завершении починки генератора вы получаете жетоны (1, максимум — 5).\n\nКаждый жетон ускоряет:\n• благословение и очистку на 10%.\n• лечение на 10%.\n• снятие выживших с крюка на 10%.",
    "img": "../assets/dbd/survivorPerks/Tier2/Flow State.png"
   },
   {
    "name": "Ради людей",
    "desc": "Если вы здоровы и лечите другого выжившего без аптечки: используйте E, чтобы мгновенно вылечить его.\n• Затем вы получаете урон.\n• Вы получаете эффект «Ослабление» на 60 сек.\n• Вы становитесь объектом одержимости.\n\nВ начале матча шанс, что убийца будет одержим вами, уменьшается.",
    "img": "../assets/dbd/survivorPerks/Tier2/For the People.png"
   },
   {
    "name": "Записки о призраке",
    "desc": "Пока на вас воздействует эффект «Усталость», ваши следы-трещины исчезают на 50% быстрее.\n\nЭффект «Усталость» спадает на 10% быстрее.",
    "img": "../assets/dbd/survivorPerks/Tier2/Ghost Notes.png"
   },
   {
    "name": "Напролом",
    "desc": "Если вы прячетесь в шкафчике не менее 3 сек., быстрый выход из него оглушит убийцу на 3 сек., если тот находится в радиусе 2.5 м. Затем вы получаете эффект «Усталость» на 40 сек.",
    "img": "../assets/dbd/survivorPerks/Tier2/Head On.png"
   },
   {
    "name": "Надежда",
    "desc": "По завершении ремонта всех генераторов вы получаете 5% эффекта «Спешка».",
    "img": "../assets/dbd/survivorPerks/Tier2/Hope.png"
   },
   {
    "name": "Железная воля",
    "desc": "Когда вы ранены и не имеете эффекта «Усталость», ваши стоны от боли звучат тише на 100%.",
    "img": "../assets/dbd/survivorPerks/Tier2/Iron Will.png"
   },
   {
    "name": "Лидер",
    "desc": "В радиусе 10 м от вас другие выжившие:\n• очищают тотемы на 30% быстрее;\n• лечат на 30% быстрее;\n• открывают ворота на 30% быстрее;\n• ломают крючья на 30% быстрее;\n• снимают товарищей с крюков на 30% быстрее;\n• открывают сундуки на 30% быстрее.\n\nКогда они отходят от вас, эффект сохраняется еще 20 сек.",
    "img": "../assets/dbd/survivorPerks/Tier2/Leader.png"
   },
   {
    "name": "Везение",
    "desc": "Если вы ранены, не более 60 сек. вы:\n• не оставляете лужи крови;\n• не оставляете следы-трещины.\n\nЗа каждую секунду, потраченную на лечение другого выжившего, восстанавливаете 1 сек. длительности.",
    "img": "../assets/dbd/survivorPerks/Tier2/Lucky Break.png"
   },
   {
    "name": "Без огласки",
    "desc": "Пока не отремонтированы все генераторы, когда вы освобождаетесь от крюка, в течение 40 сек.:\n• на вас действует эффект «Стойкость»;\n• ваши стоны от боли звучат на 100% тише;\n• убийца не видит вашу ауру.",
    "img": "../assets/dbd/survivorPerks/Tier2/Off the Record.png"
   },
   {
    "name": "Раз, два, три, четыре!",
    "desc": "При бездействии нажмите F, чтобы начать представление и приободрить всех выживших в радиусе 16 м на 15 сек. Пока вы выступаете, остальные выжившие видят вашу ауру. В это время вы проходите особые проверки реакции. При лечении или починке базовые проверки реакции появляются на 20% чаще.\n\nЕсли вы успешно завершите представление, его эффект сохранится на 90 сек. Перезарядка: 90 сек.",
    "img": "../assets/dbd/survivorPerks/Tier2/One-Two-Three-Four.png"
   },
   {
    "name": "Прояви себя",
    "desc": "Скорость ремонта всех выживших увеличивается на 10% за каждого выжившего в радиусе 4 м.",
    "img": "../assets/dbd/survivorPerks/Tier2/Prove Thyself.png"
   },
   {
    "name": "Быстрый гамбит",
    "desc": "Когда убийца вас преследует:\n• вы видите ауры остальных выживших;\n• те ремонтируют генераторы на 5% быстрее.\n\nКогда вы получаете урон, эффект перезаряжается: 40 сек.",
    "img": "../assets/dbd/survivorPerks/Tier2/Quick Gambit.png"
   },
   {
    "name": "Ободрение",
    "desc": "Стоя в 6 м от выжившего на крюке, нажмите F, чтобы остановить прогресс жертвоприношения на 30 сек. Срабатывает только раз для каждого крюка.",
    "img": "../assets/dbd/survivorPerks/Tier2/Reassurance.png"
   },
   {
    "name": "Устойчивость",
    "desc": "Когда вы ранены:\n• благословение и очистка тотемов ускоряются на 9%;\n• лечение ускоряется на 9%;\n• скорость открытия ворот увеличивается на 9%;\n• скорость починки увеличивается на 9%;\n• вы ломаете крюки на 9% быстрее;\n• вы снимаете выживших с крюка на 9% быстрее;\n• вы открываете сундуки на 9% быстрее;\n• вы прыгаете на 9% быстрее.",
    "img": "../assets/dbd/survivorPerks/Tier2/Resilience.png"
   },
   {
    "name": "Второе дыхание",
    "desc": "Если вы исцелили выжившего на 1 стадию здоровья, не имея эффекта «Ослабление», то когда вас снимают с крюка, вы получаете эффект «Ослабление».\n\nЕсли вы не получите смертельного ранения в течение 20 сек., то мгновенно исцелитесь.",
    "img": "../assets/dbd/survivorPerks/Tier2/Second Wind.png"
   },
   {
    "name": "Выслеживание подозреваемого",
    "desc": "Если вы прячетесь в радиусе террора убийцы в течение 15 сек., то получаете жетоны (1, максимум — 4).\n\nКогда вы хорошо проходите базовую проверку реакции, тратятся жетоны (1):\n• хорошая проверка становится отличной;\n• вы получаете на 1% больше прогресса.",
    "img": "../assets/dbd/survivorPerks/Tier2/Stake Out.png"
   },
   {
    "name": "Бессонница",
    "desc": "Все выжившие в радиусе 16 м от вас:\n• теряют эффект «Слепота» на 66% быстрее;\n• теряют эффект «Ослабление» на 66% быстрее;\n• теряют эффект «Усталость» на 66% быстрее;\n• теряют эффект «Уязвимость» на 66% быстрее;\n• теряют эффект «Кровотечение» на 66% быстрее;\n• теряют эффект «Замедление» на 66% быстрее;\n• теряют эффект «Травма» на 66% быстрее;\n• теряют эффект «Забывчивость» на 66% быстрее.\n\nКогда вы отойдете, эффект сохранится еще на 15 сек.",
    "img": "../assets/dbd/survivorPerks/Tier2/Vigil.png"
   },
   {
    "name": "Мы справимся",
    "desc": "После того, как вы снимаете выжившего с крюка, вы лечите остальных на 90% быстрее в течение 100 сек.",
    "img": "../assets/dbd/survivorPerks/Tier2/We_ll Make It.png"
   },
   {
    "name": "Мы будем жить вечно",
    "desc": "Вы лечите смертельно раненых выживших на 100% быстрее.\n\nКогда лечение смертельно раненого заканчивается, он получает эффект «Стойкость» на 10 сек. Перезарядка: 30 сек.",
    "img": "../assets/dbd/survivorPerks/Tier2/We_re Gonna Live Forever.png"
   },
   {
    "name": "Уникальная возможность",
    "desc": "В радиусе 32 м:\n• вы видите ауры досок;\n• вы видите ауры разрушаемых стен;\n• вы видите ауры окон.",
    "img": "../assets/dbd/survivorPerks/Tier2/Windows of Opportunity.png"
   }
  ],
  "3": [
   {
    "name": "Адреналин",
    "desc": "Если вы смертельно или просто ранены в момент завершения ремонта всех генераторов, то мгновенно исцеляетесь. После этого игнорируется эффект «Усталость»:\n• вы получаете 50% эффекта «Спешка» на 3 сек.;\n• получаете эффект «Усталость» на 40 сек.",
    "img": "../assets/dbd/survivorPerks/Tier3/Adrenaline.png"
   },
   {
    "name": "Ловкое приземление",
    "desc": "Когда вы падаете с высоты не менее 1.2 м:\n• вы получаете 50% эффекта «Спешка» на 3 сек.;\n• вы получаете эффект «Усталость» на 40 сек.;\n• ваше оглушение проходит на 75% быстрее;\n• ваши стоны от падения звучат на 100% тише.",
    "img": "../assets/dbd/survivorPerks/Tier3/Balanced Landing.png"
   },
   {
    "name": "Крепкий орешек",
    "desc": "Покидая крюк, имея ранение и бегая, нажмите E:\n• вы получаете эффект «Стойкость» на 0.5 сек.;\n• вы получаете эффект «Усталость» на 40 сек.",
    "img": "../assets/dbd/survivorPerks/Tier3/Dead Hard.png"
   },
   {
    "name": "Решающий удар",
    "desc": "Когда вас снимают с крюка, но не все генераторы еще отремонтированы, то в течение следующих 60 сек.: когда убийца хватает вас, один раз за матч вы должны пройти особую проверку реакции, и в случае успеха вы:\n• оглушите убийцу на 4 сек.;\n• станете объектом его одержимости.\n\nДействия, привлекающие внимание, отменяют этот эффект. В начале матча у вас больше шансов стать объектом одержимости.",
    "img": "../assets/dbd/survivorPerks/Tier3/Decisive Strike.png"
   },
   {
    "name": "Дежавю",
    "desc": "Вы видите ауры генераторов (3), которые стоят ближе всего друг к другу, а починка этих генераторов ускоряется на 6%.",
    "img": "../assets/dbd/survivorPerks/Tier3/Deja Vu.png"
   },
   {
    "name": "Освобождение",
    "desc": "Один раз за матч, когда безопасно снимаете товарища с крюка, вы получаете возможность слезть с крюка самостоятельно. Использовав эту возможность, вы получаете эффект «Ослабление» на 60 сек.",
    "img": "../assets/dbd/survivorPerks/Tier3/Deliverance.png"
   },
   {
    "name": "Драматургия",
    "desc": "Если вы здоровы и бежите, нажмите E, чтобы:\n• получить 25% эффекта «Спешка» на 2 сек.;\n• получить эффект «Усталость» на 40 сек.\n\nЗатем происходит одно из случайных событий:\n• вы получаете 25% эффекта «Спешка» на 2 сек.;\n• вы получаете эффект «Уязвимость» на 12 сек.;\n• вы получаете случайный редкий предмет со случайными улучшениями;\n• вы кричите, но ничего не происходит.\n\nОдин и тот же эффект не может произойти два раза подряд.",
    "img": "../assets/dbd/survivorPerks/Tier3/Dramaturgy.png"
   },
   {
    "name": "Полная сосредоточенность",
    "desc": "Если вы отлично проходите базовую проверку реакции, то получаете жетоны (1 шт., максимум — 6).\n\nЗа каждый жетон базовые проверки реакции:\n• происходят на 4% чаще;\n• проходят на 4% быстрее;\n• дают +30% к прогрессу за отличное прохождение.\n\nВы потеряете все жетоны, если провалите базовую проверку, пройдете ее хорошо или прекратите ремонт.",
    "img": "../assets/dbd/survivorPerks/Tier3/Hyperfocus.png"
   },
   {
    "name": "Гибкость",
    "desc": "После прыжков на средней или большой скорости вы получаете:\n• 50% эффекта «Спешка» на 3 сек.;\n• эффект «Усталость» на 40 сек.",
    "img": "../assets/dbd/survivorPerks/Tier3/Lithe.png"
   },
   {
    "name": "Преодоление",
    "desc": "Когда вы получаете урон:\n• повышение скорости действует на 2 сек. дольше.\n• Вы получаете эффект «Усталость» на 40 сек.",
    "img": "../assets/dbd/survivorPerks/Tier3/Overcome.png"
   },
   {
    "name": "Вот это поворот",
    "desc": "Если вы ранены, пригнулись и бездействуете, нажмите F, чтобы бесшумно получить смертельное ранение.\n\nПолучив смертельное ранение таким образом, вы один раз за матч:\n• не стонете от боли;\n• не оставляете лужи крови;\n• восстанавливаетесь на 25% быстрее;\n• можете восстановиться полностью.\n\nВосстановившись таким образом, вы:\n• получаете 50% эффекта «Спешка» на 4 сек.;\n• мгновенно восстанавливаете здоровье.\n\nСпособность снова становится доступна по завершении ремонта всех генераторов.",
    "img": "../assets/dbd/survivorPerks/Tier3/Plot Twist.png"
   },
   {
    "name": "Поправка",
    "desc": "Когда вас снимают с крюка, вы получаете 70% прогресса лечения.",
    "img": "../assets/dbd/survivorPerks/Tier3/Resurgence.png"
   },
   {
    "name": "Бремя на себя",
    "desc": "Один раз за матч, если вы не имеете 2-й стадии крюка и стоите рядом с подвешенным товарищем, нажмите F, чтобы его освободить. Затем:\n• он теряет одну стадию крюка;\n• вы получаете одну стадию крюка;\n• вы кричите;\n• вы получаете эффект «Уязвимость» на 40 сек.",
    "img": "../assets/dbd/survivorPerks/Tier3/Shoulder the Burden.png"
   },
   {
    "name": "Ударный забег",
    "desc": "Если вы оглушаете убийцу доской, то:\n• получаете 50% эффекта «Спешка» на 4 сек.;\n• получаете эффект «Усталость» на 20 сек.",
    "img": "../assets/dbd/survivorPerks/Tier3/Smash Hit.png"
   },
   {
    "name": "Спринтер",
    "desc": "Когда вы переходите на бег, то:\n• получаете 50% эффекта «Спешка» на 3 сек.\n• Получаете эффект «Усталость» на 40 сек.",
    "img": "../assets/dbd/survivorPerks/Tier3/Sprint Burst.png"
   },
   {
    "name": "Несокрушимый",
    "desc": "Один раз за матч вы можете полностью исцелиться от смертельного ранения, нанесенного вам убийцей.\n\nСо смертельным ранением вы восстанавливаетесь на 35% быстрее.",
    "img": "../assets/dbd/survivorPerks/Tier3/Unbreakable.png"
   }
  ]
 },
 "items": [
  {
   "name": "Аптечка лесничего",
   "cat": "Аптечки",
   "rarity": "Очень редкий",
   "price": 500,
   "img": "../assets/dbd/items/Medkits/Ranger Med Kit.png"
  },
  {
   "name": "Инструменты Алекс",
   "cat": "Инструменты",
   "rarity": "Очень редкий",
   "price": 500,
   "img": "../assets/dbd/items/Toolboxes/Alex_s Toolbox.png"
  },
  {
   "name": "Инструменты инженера",
   "cat": "Инструменты",
   "rarity": "Очень редкий",
   "price": 500,
   "img": "../assets/dbd/items/Toolboxes/Engineer_s Toolbox.png"
  },
  {
   "name": "Спортивный фонарик",
   "cat": "Фонарики",
   "rarity": "Редкий",
   "price": 400,
   "img": "../assets/dbd/items/Flashlights/Sport Flashlight.png"
  },
  {
   "name": "Практичный фонарик",
   "cat": "Фонарики",
   "rarity": "Очень редкий",
   "price": 500,
   "img": "../assets/dbd/items/Flashlights/Utility Flashlight.png"
  },
  {
   "name": "Ключ скелета",
   "cat": "Ключи",
   "rarity": "Редкий",
   "price": 400,
   "img": "../assets/dbd/items/Keys/Skeleton Key.png"
  },
  {
   "name": "Карта с подписями",
   "cat": "Карты",
   "rarity": "Редкий",
   "price": 400,
   "img": "../assets/dbd/items/Maps/Annotated Map.png"
  },
  {
   "name": "Флакон подмастерья с туманом",
   "cat": "Флаконы с туманом",
   "rarity": "Обычный",
   "price": 300,
   "img": "../assets/dbd/items/Fog Vials/Apprentice_s Fog Vial.png"
  },
  {
   "name": "Флакон мастерового с туманом",
   "cat": "Флаконы с туманом",
   "rarity": "Необычный",
   "price": 350,
   "img": "../assets/dbd/items/Fog Vials/Artisan_s Fog Vial.png"
  },
  {
   "name": "Флакон Виго с туманом",
   "cat": "Флаконы с туманом",
   "rarity": "Редкий",
   "price": 400,
   "img": "../assets/dbd/items/Fog Vials/Vigo_s Fog Vial.png"
  },
  {
   "name": "Праздничная петарда",
   "cat": "Петарды",
   "rarity": "Событие",
   "price": 250,
   "img": "../assets/dbd/items/Firecrackers/Third Year Party Starter.png"
  }
 ],
 "survivors": [
  {
   "name": "Дуайт Фэйрфилд",
   "img": "../assets/dbd/survivorIcons/Dwight Fairfield.png"
  },
  {
   "name": "Мэг Томас",
   "img": "../assets/dbd/survivorIcons/Meg Thomas.png"
  },
  {
   "name": "Клодетт Морель",
   "img": "../assets/dbd/survivorIcons/Claudette Morel.png"
  },
  {
   "name": "Джейк Парк",
   "img": "../assets/dbd/survivorIcons/Jake Park.png"
  },
  {
   "name": "Нея Карлссон",
   "img": "../assets/dbd/survivorIcons/Nea Karlsson.png"
  },
  {
   "name": "Лори Строуд",
   "img": "../assets/dbd/survivorIcons/Laurie Strode.png"
  },
  {
   "name": "Эйс Висконти",
   "img": "../assets/dbd/survivorIcons/Ace Visconti.png"
  },
  {
   "name": "Уильям «Билл» Овербек",
   "img": "../assets/dbd/survivorIcons/Bill Overbeck.png"
  },
  {
   "name": "Фенг Мин",
   "img": "../assets/dbd/survivorIcons/Feng Min.png"
  },
  {
   "name": "Дэвид Кинг",
   "img": "../assets/dbd/survivorIcons/David King.png"
  },
  {
   "name": "Квентин Смит",
   "img": "../assets/dbd/survivorIcons/Quentin Smith.png"
  },
  {
   "name": "Детектив Тэпп",
   "img": "../assets/dbd/survivorIcons/David Tapp.png"
  },
  {
   "name": "Кейт Денсон",
   "img": "../assets/dbd/survivorIcons/Kate Denson.png"
  },
  {
   "name": "Адам Фрэнсис",
   "img": "../assets/dbd/survivorIcons/Adam Francis.png"
  },
  {
   "name": "Джефф Йохансен",
   "img": "../assets/dbd/survivorIcons/Jeff Johansen.png"
  },
  {
   "name": "Джейн Ромеро",
   "img": "../assets/dbd/survivorIcons/Jane Romero.png"
  },
  {
   "name": "Эшли Джей Уильямс",
   "img": "../assets/dbd/survivorIcons/Ash Williams.png"
  },
  {
   "name": "Нэнси Уиллер",
   "img": "../assets/dbd/survivorIcons/Nancy Wheeler.png"
  },
  {
   "name": "Стив Харрингтон",
   "img": "../assets/dbd/survivorIcons/Steve Harrington.png"
  },
  {
   "name": "Юи Кимура",
   "img": "../assets/dbd/survivorIcons/Yui Kimura.png"
  },
  {
   "name": "Зарина Кассир",
   "img": "../assets/dbd/survivorIcons/Zarina Kassir.png"
  },
  {
   "name": "Шерил Мейсон",
   "img": "../assets/dbd/survivorIcons/Cheryl Mason.png"
  },
  {
   "name": "Феликс Рихтер",
   "img": "../assets/dbd/survivorIcons/Felix Richter.png"
  },
  {
   "name": "Элоди Ракото",
   "img": "../assets/dbd/survivorIcons/Elodie Rakoto.png"
  },
  {
   "name": "Ли Юнчин",
   "img": "../assets/dbd/survivorIcons/Yun-Jin Lee.png"
  },
  {
   "name": "Джилл Валентайн",
   "img": "../assets/dbd/survivorIcons/Jill Valentine.png"
  },
  {
   "name": "Леон С. Кеннеди",
   "img": "../assets/dbd/survivorIcons/Leon S Kennedy.png"
  },
  {
   "name": "Микаэла Рид",
   "img": "../assets/dbd/survivorIcons/Mikaela Reid.png"
  },
  {
   "name": "Хонас Васкес",
   "img": "../assets/dbd/survivorIcons/Jonah Vasquez.png"
  },
  {
   "name": "Ёити Асакава",
   "img": "../assets/dbd/survivorIcons/Yoichi Asakawa.png"
  },
  {
   "name": "Хэдди Каур",
   "img": "../assets/dbd/survivorIcons/Haddie Kaur.png"
  },
  {
   "name": "Ада Вонг",
   "img": "../assets/dbd/survivorIcons/Ada Wong.png"
  },
  {
   "name": "Ребекка Чемберс",
   "img": "../assets/dbd/survivorIcons/Rebecca Chambers.png"
  },
  {
   "name": "Витторио Тоскано",
   "img": "../assets/dbd/survivorIcons/Vittorio Toscano.png"
  },
  {
   "name": "Талита Лира",
   "img": "../assets/dbd/survivorIcons/Thalita Lyra.png"
  },
  {
   "name": "Ренато Лира",
   "img": "../assets/dbd/survivorIcons/Renato Lyra.png"
  },
  {
   "name": "Габриэль Сома",
   "img": "../assets/dbd/survivorIcons/Gabriel Soma.png"
  },
  {
   "name": "Николас Кейдж",
   "img": "../assets/dbd/survivorIcons/Nicolas Cage.png"
  },
  {
   "name": "Эллен Рипли",
   "img": "../assets/dbd/survivorIcons/Ellen Ripley.png"
  },
  {
   "name": "Алан Уэйк",
   "img": "../assets/dbd/survivorIcons/Alan Wake.png"
  },
  {
   "name": "Сейбл Уорд",
   "img": "../assets/dbd/survivorIcons/Sable Ward.png"
  },
  {
   "name": "Аэстри Язар",
   "img": "../assets/dbd/survivorIcons/Aestri Yazar.png"
  },
  {
   "name": "Лара Крофт",
   "img": "../assets/dbd/survivorIcons/Lara Croft.png"
  },
  {
   "name": "Тревор Бельмонт",
   "img": "../assets/dbd/survivorIcons/Trevor Belmont.png"
  },
  {
   "name": "Тори Кейн",
   "img": "../assets/dbd/survivorIcons/Taurie Cain.png"
  },
  {
   "name": "Орела Роуз",
   "img": "../assets/dbd/survivorIcons/Orela Rose.png"
  },
  {
   "name": "Рик Граймс",
   "img": "../assets/dbd/survivorIcons/Rick Grimes.png"
  },
  {
   "name": "Мишон Граймс",
   "img": "../assets/dbd/survivorIcons/Michonne Grimes.png"
  },
  {
   "name": "Ви Бунясак",
   "img": "../assets/dbd/survivorIcons/Vee Boonyasak.png"
  },
  {
   "name": "Дастин Хендерсон",
   "img": "../assets/dbd/survivorIcons/Dustin Henderson.png"
  },
  {
   "name": "Одиннадцать",
   "img": "../assets/dbd/survivorIcons/Eleven.png"
  },
  {
   "name": "Квон Тхэён",
   "img": "../assets/dbd/survivorIcons/Kwon Tae-young.png"
  },
  {
   "name": "Шейн Виигваас",
   "img": "../assets/dbd/survivorIcons/Shane Wiigwaas.webp"
  }
 ],
 "killers": [
  {
   "name": "ОХОТНИК",
   "img": "../assets/dbd/killerIcons/Trapper.png"
  },
  {
   "name": "ПРИЗРАК",
   "img": "../assets/dbd/killerIcons/Wraith.png"
  },
  {
   "name": "ДЕРЕВЕНЩИНА",
   "img": "../assets/dbd/killerIcons/Hillbilly.png"
  },
  {
   "name": "МЕДСЕСТРА",
   "img": "../assets/dbd/killerIcons/Nurse.png"
  },
  {
   "name": "ТЕНЬ",
   "img": "../assets/dbd/killerIcons/Shape Variant.png"
  },
  {
   "name": "ВЕДЬМА",
   "img": "../assets/dbd/killerIcons/Hag.png"
  },
  {
   "name": "ДОКТОР",
   "img": "../assets/dbd/killerIcons/Doctor.png"
  },
  {
   "name": "ОХОТНИЦА",
   "img": "../assets/dbd/killerIcons/Huntress.png"
  },
  {
   "name": "КАННИБАЛ",
   "img": "../assets/dbd/killerIcons/Cannibal.png"
  },
  {
   "name": "КОШМАР",
   "img": "../assets/dbd/killerIcons/Nightmare.png"
  },
  {
   "name": "СВИНЬЯ",
   "img": "../assets/dbd/killerIcons/Pig.png"
  },
  {
   "name": "КЛОУН",
   "img": "../assets/dbd/killerIcons/Clown.png"
  },
  {
   "name": "ДУХ",
   "img": "../assets/dbd/killerIcons/Spirit.png"
  },
  {
   "name": "ЛЕГИОН",
   "img": "../assets/dbd/killerIcons/Legion.png"
  },
  {
   "name": "ЧУМА",
   "img": "../assets/dbd/killerIcons/Plague.png"
  },
  {
   "name": "ГОУСТ ФЕЙС",
   "img": "../assets/dbd/killerIcons/Ghostface.png"
  },
  {
   "name": "ДЕМОГОРГОН",
   "img": "../assets/dbd/killerIcons/Demogorgon.png"
  },
  {
   "name": "ОНИ",
   "img": "../assets/dbd/killerIcons/Oni.png"
  },
  {
   "name": "СТРЕЛОК",
   "img": "../assets/dbd/killerIcons/Deathslinger.png"
  },
  {
   "name": "ПАЛАЧ",
   "img": "../assets/dbd/killerIcons/Executioner.png"
  },
  {
   "name": "МОР",
   "img": "../assets/dbd/killerIcons/Blight.png"
  },
  {
   "name": "БЛИЗНЕЦЫ",
   "img": "../assets/dbd/killerIcons/Twins.png"
  },
  {
   "name": "ТРЮКАЧ",
   "img": "../assets/dbd/killerIcons/Trickster.png"
  },
  {
   "name": "НЕМЕЗИС",
   "img": "../assets/dbd/killerIcons/Nemesis.png"
  },
  {
   "name": "СЕНОБИТ",
   "img": "../assets/dbd/killerIcons/Cenobite.png"
  },
  {
   "name": "ХУДОЖНИЦА",
   "img": "../assets/dbd/killerIcons/Artist.png"
  },
  {
   "name": "ОНРЁ",
   "img": "../assets/dbd/killerIcons/Onryo.png"
  },
  {
   "name": "ГРЯЗЬ",
   "img": "../assets/dbd/killerIcons/Dredge.png"
  },
  {
   "name": "КУКЛОВОД",
   "img": "../assets/dbd/killerIcons/Mastermind.png"
  },
  {
   "name": "РЫЦАРЬ",
   "img": "../assets/dbd/killerIcons/Knight.png"
  },
  {
   "name": "ТОРГОВКА ЧЕРЕПАМИ",
   "img": "../assets/dbd/killerIcons/Skull Merchant.png"
  },
  {
   "name": "СИНГУЛЯРНОСТЬ",
   "img": "../assets/dbd/killerIcons/Singularity.png"
  },
  {
   "name": "КСЕНОМОРФ",
   "img": "../assets/dbd/killerIcons/Xenomorph.png"
  },
  {
   "name": "ХОРОШИЙ ПАРЕНЬ",
   "img": "../assets/dbd/killerIcons/Good Guy.png"
  },
  {
   "name": "НЕВЕДОМОЕ",
   "img": "../assets/dbd/killerIcons/Unknown.png"
  },
  {
   "name": "ЛИЧ",
   "img": "../assets/dbd/killerIcons/Lich.png"
  },
  {
   "name": "ТЕМНЫЙ ВЛАСТЕЛИН",
   "img": "../assets/dbd/killerIcons/Dark Lord.png"
  },
  {
   "name": "ЕГЕРЬ",
   "img": "../assets/dbd/killerIcons/Houndmaster.png"
  },
  {
   "name": "ГУЛЬ",
   "img": "../assets/dbd/killerIcons/Ghoul.png"
  },
  {
   "name": "АНИМАТРОНИК",
   "img": "../assets/dbd/killerIcons/Animatronic.png"
  },
  {
   "name": "КРАСУ",
   "img": "../assets/dbd/killerIcons/Krasue.png"
  },
  {
   "name": "ПЕРВЫЙ",
   "img": "../assets/dbd/killerIcons/T_UI_K42_TheFirst_Portrait.png"
  },
  {
   "name": "СЛЭШЕР",
   "img": "../assets/dbd/killerIcons/Slasher.png"
  }
 ]
};
