/**
 * roulette_app.jsx — standalone DBD casino roulette.
 *
 * Everything the server used to do is ported here, with no API/network at all:
 *   - perk roll      — modules/rolls.py trigger_roll + perk_randomizer.roll_random_perks
 *   - character roll — modules/rolls.py trigger_character_roll (escalating jackpot
 *                      chance: 15% base, +15% per miss)
 *   - spin visuals   — overlay useOverlaySSE handleCharacterSpinStep (jackpot = all
 *                      4 reels on the winner; miss = 4 different random characters)
 *
 * The character sequence is rolled ONE SPIN AT A TIME rather than precomputed
 * like the server did. Statistically identical, but nothing anywhere knows how
 * many spins are left — so nothing can leak it to the viewers.
 *
 * Data (perk pools, icon lists) comes from data/library.js, generated by
 * tools/generate_library.py — regenerate it after adding/removing images.
 */
import { useState, useMemo, useCallback, useRef, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import { SlotMachine } from './SlotMachine.jsx';
import { setMasterVolume, stopAllOverlaySounds } from './audio.js';

const D = window.ROULETTE_DATA || {};

const BASE_JACKPOT_CHANCE = 15;   // percent, matches rolls.py
const VOLUME_KEY = 'ro_volume';
const PANEL_KEY = 'ro_panel_hidden';

function choice(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function sampleUnique(arr, n) {
  const copy = [...arr];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy.slice(0, Math.min(n, copy.length));
}

// localStorage is unavailable/throwing on some file:// setups — never let a
// settings read take the whole page down.
function loadSetting(key, fallback) {
  try {
    const v = localStorage.getItem(key);
    return v === null ? fallback : v;
  } catch (_) {
    return fallback;
  }
}

function saveSetting(key, value) {
  try { localStorage.setItem(key, value); } catch (_) {}
}

const MODES = [
  { key: 'perksSurvivor', label: 'Перки: выживший' },
  { key: 'perksKiller',   label: 'Перки: убийца' },
  { key: 'survivors',     label: 'Рулетка: выжившие' },
  { key: 'killers',       label: 'Рулетка: убийцы' },
];

const IDLE_HINT = 'Дёрни рычаг →';

function isPerks(mode) {
  return mode === 'perksSurvivor' || mode === 'perksKiller';
}

// Idle cabinet for a mode: on screen, reels filled, waiting for a pull.
function idleSlot(mode) {
  const perkMode = isPerks(mode);
  return {
    visible: true,
    mode: perkMode ? 'perks' : 'character',
    role: mode === 'perksKiller' ? 'killer' : 'survivor',
    perks: null,
    charLibrary: perkMode
      ? null
      : (mode === 'killers' ? (D.killerCharacters || []) : (D.survivorCharacters || [])),
    isJackpot: false,
    characterName: '',
    spinIndex: -1,
  };
}

function App() {
  const [mode, setMode] = useState('perksSurvivor');
  const [slot, setSlot] = useState(() => idleSlot('perksSurvivor'));
  const [spinning, setSpinning] = useState(false);
  const [status, setStatus] = useState(IDLE_HINT);
  const [panelHidden, setPanelHidden] = useState(() => loadSetting(PANEL_KEY, '0') === '1');
  const [volume, setVolume] = useState(() => {
    const v = parseFloat(loadSetting(VOLUME_KEY, '1'));
    return Number.isFinite(v) ? Math.max(0, Math.min(1, v)) : 1;
  });
  const [lastVolume, setLastVolume] = useState(1);

  // Bumped on every mode switch and passed as SlotMachine's key, which forces
  // a real unmount instead of the component merely rendering null. Rendering
  // null keeps the instance (and its state) alive — that's what let a golden
  // glow survive into the next roulette and let a mid-roll spin keep running
  // its sounds. A remount is the one thing that can't leak either.
  const [cabinetKey, setCabinetKey] = useState(0);
  // Pending "show the fresh cabinet" timer, so switching back and forth fast
  // can't stack timers that fight over what's on screen.
  const showTimerRef = useRef(null);

  // Live character sequence: { winner, chance }. Null between sequences — the
  // next pull starts a fresh one with a new winner.
  const seqRef = useRef(null);
  // What the reels are about to land on, read once they settle so the status
  // can't spoil the result mid-spin.
  const pendingRef = useRef(null);

  useEffect(() => () => clearTimeout(showTimerRef.current), []);

  // ── Sound ─────────────────────────────────────────────────────────────────
  useEffect(() => {
    setMasterVolume(volume);
    saveSetting(VOLUME_KEY, String(volume));
  }, [volume]);

  useEffect(() => {
    saveSetting(PANEL_KEY, panelHidden ? '1' : '0');
    // On phones app.css carves out space for the panel; when it's hidden,
    // this class gives the whole screen back to the cabinet.
    document.body.classList.toggle('ro-panel-hidden', panelHidden);
  }, [panelHidden]);

  const toggleMute = useCallback(() => {
    setVolume(v => {
      if (v > 0) { setLastVolume(v); return 0; }
      return lastVolume > 0 ? lastVolume : 1;
    });
  }, [lastVolume]);

  // Reel-fill library, same per-role restriction as overlay_app's slotLibrary.
  const slotLibrary = useMemo(() => {
    if (slot.mode === 'character') return slot.charLibrary;
    return slot.role === 'killer' ? (D.killerPerkLibrary || []) : (D.survivorPerkLibrary || []);
  }, [slot.mode, slot.charLibrary, slot.role]);

  // ── Lever pull ────────────────────────────────────────────────────────────
  const handlePull = useCallback(() => {
    if (spinning) return;

    if (isPerks(mode)) {
      // Port of /api/roll: 4 unique perks from the role's pool.
      const pool = mode === 'perksKiller' ? (D.killerPerkPool || []) : (D.survivorPerkPool || []);
      if (pool.length < 4) {
        setStatus('Нет данных перков — запусти tools/generate_library.py');
        return;
      }
      const perks = sampleUnique(pool, 4).map(p => ({ name: p.name, image: p.image }));
      pendingRef.current = { kind: 'perks', names: perks.map(p => p.name) };
      setSpinning(true);
      setStatus('Крутится…');
      setSlot(prev => ({
        ...prev,
        visible: true,
        perks,
        isJackpot: false,
        characterName: '',
        spinIndex: prev.spinIndex + 1,
      }));
      return;
    }

    // Port of /api/roll_character, evaluated one spin at a time.
    const chars = mode === 'killers' ? (D.killerCharacters || []) : (D.survivorCharacters || []);
    if (chars.length < 2) {
      setStatus('Мало иконок персонажей — запусти tools/generate_library.py');
      return;
    }
    if (!seqRef.current) {
      seqRef.current = { winner: choice(chars), chance: BASE_JACKPOT_CHANCE };
    }
    const seq = seqRef.current;
    const jackpot = Math.floor(Math.random() * 100) < seq.chance;
    const character = jackpot ? seq.winner : choice(chars);

    if (jackpot) {
      seqRef.current = null;              // next pull starts a new sequence
    } else {
      seq.chance += BASE_JACKPOT_CHANCE;  // escalate, exactly like the server
    }

    // Jackpot → all 4 reels on the winner. Miss → 4 different characters.
    let finalReels;
    if (jackpot) {
      finalReels = Array(4).fill({ image: character.image, name: character.name });
    } else if (chars.length >= 4) {
      finalReels = [...chars].sort(() => 0.5 - Math.random())
        .slice(0, 4)
        .map(c => ({ image: c.image, name: c.name }));
    } else {
      finalReels = Array(4).fill({ image: character.image, name: character.name });
    }

    pendingRef.current = { kind: 'char', jackpot, name: character.name };
    setSpinning(true);
    setStatus('Крутится…');
    setSlot(prev => ({
      ...prev,
      visible: true,
      perks: finalReels,
      charLibrary: chars,
      isJackpot: jackpot,
      characterName: character.name,
      spinIndex: prev.spinIndex + 1,
    }));
  }, [spinning, mode]);

  // ── Reels settled — cabinet stays on screen, just report the result ───────
  const handleComplete = useCallback(() => {
    setSpinning(false);
    const res = pendingRef.current;
    if (!res) { setStatus(IDLE_HINT); return; }
    if (res.kind === 'perks') {
      setStatus(res.names.join(', '));
    } else {
      setStatus(res.jackpot ? `🎉 Победитель: ${res.name}!` : 'Мимо! Дёрни рычаг ещё раз.');
    }
  }, []);

  // ── Mode switch — the ONE thing that hides the cabinet ────────────────────
  // Everything a spin can leave behind dies here: the sequence, the pending
  // result, any sound mid-flight, and (via the key bump) the cabinet's own
  // state. Safe to hammer — switching back and forth, or mid-roll, just
  // restarts this.
  const changeMode = useCallback((key) => {
    clearTimeout(showTimerRef.current);
    stopAllOverlaySounds();
    seqRef.current = null;
    pendingRef.current = null;
    setSpinning(false);
    setMode(key);
    setStatus(IDLE_HINT);
    setCabinetKey(k => k + 1);
    setSlot(prev => ({ ...prev, visible: false }));
    // Brief blackout, then the fresh cabinet slides in with the new icons.
    showTimerRef.current = setTimeout(() => setSlot(idleSlot(key)), 280);
  }, []);

  const volPct = Math.round(volume * 100);

  return (
    <>
      {panelHidden ? (
        <button
          className="ro-show-btn"
          onClick={() => setPanelHidden(false)}
          title="Показать панель"
        >🎰</button>
      ) : (
        <div className="ro-panel">
          <div className="ro-head">
            <div className="ro-title">🎰 DBD Рулетка</div>
            <button
              className="ro-hide-btn"
              onClick={() => setPanelHidden(true)}
              title="Скрыть панель"
            >✕</button>
          </div>

          <div className="ro-modes">
            {MODES.map(m => (
              <button
                key={m.key}
                className={`ro-mode-btn ${mode === m.key ? 'active' : ''}`}
                onClick={() => changeMode(m.key)}
              >{m.label}</button>
            ))}
          </div>

          <div className="ro-sound">
            <button className="ro-mute-btn" onClick={toggleMute} title="Выключить звук">
              {volume === 0 ? '🔇' : '🔊'}
            </button>
            <input
              className="ro-vol"
              type="range"
              min="0"
              max="100"
              value={volPct}
              onChange={e => setVolume(Number(e.target.value) / 100)}
              title="Громкость"
            />
            <span className="ro-vol-num">{volPct}%</span>
          </div>

          <div className="ro-status">{status}</div>

          {/* Живёт в панели, а не поверх экрана: на стриме панель скрыта (✕),
              значит и ссылка зрителям не видна. */}
          <a className="ro-back" href="../">← На главную</a>
        </div>
      )}

      <SlotMachine
        key={cabinetKey}
        visible={slot.visible}
        mode={slot.mode}
        perks={slot.perks}
        library={slotLibrary}
        isJackpot={slot.isJackpot}
        characterName={slot.characterName}
        spinIndex={slot.spinIndex}
        canPull={!spinning}
        onPull={handlePull}
        onComplete={handleComplete}
      />
    </>
  );
}

createRoot(document.getElementById('root')).render(<App />);
